// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_posts.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countListingsForAdmin = `-- name: CountListingsForAdmin :one
SELECT count(*)
FROM listings l
WHERE ($1::text IS NULL
       OR l.search @@ websearch_to_tsquery('english', $1::text))
  AND ($2::text  IS NULL OR l.status = $2::text)
  AND ($3::bool IS NULL OR (l.removed_at IS NOT NULL) = $3::bool)
  AND ($4::uuid IS NULL OR l.owner_id = $4::uuid)
`

type CountListingsForAdminParams struct {
	Search  *string
	Status  *string
	Removed *bool
	OwnerID *uuid.UUID
}

func (q *Queries) CountListingsForAdmin(ctx context.Context, arg CountListingsForAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countListingsForAdmin,
		arg.Search,
		arg.Status,
		arg.Removed,
		arg.OwnerID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequestsForAdmin = `-- name: CountRequestsForAdmin :one
SELECT count(*)
FROM housing_requests r
WHERE ($1::text IS NULL
       OR r.search @@ websearch_to_tsquery('english', $1::text))
  AND ($2::text  IS NULL OR r.status = $2::text)
  AND ($3::bool IS NULL OR (r.removed_at IS NOT NULL) = $3::bool)
  AND ($4::uuid IS NULL OR r.poster_id = $4::uuid)
`

type CountRequestsForAdminParams struct {
	Search  *string
	Status  *string
	Removed *bool
	OwnerID *uuid.UUID
}

func (q *Queries) CountRequestsForAdmin(ctx context.Context, arg CountRequestsForAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestsForAdmin,
		arg.Search,
		arg.Status,
		arg.Removed,
		arg.OwnerID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listListingsForAdmin = `-- name: ListListingsForAdmin :many

SELECT
    l.id, l.owner_id, l.title, l.body, l.conditions, l.price_cents, l.deposit_cents, l.start_date, l.end_date, l.lease_months, l.term_tag, l.unit_type, l.bedrooms_total, l.bedroom_of, l.bathrooms, l.bath_type, l.furnished, l.utilities, l.parking, l.pets, l.laundry, l.address_line, l.neighbourhood, l.lat, l.lng, l.distance_m, l.commute_minutes, l.commute_mode, l.minutes_to_transit, l.minutes_to_grocery, l.status, l.views, l.replies, l.saves, l.created_at, l.updated_at, l.search, l.published_at, l.removed_at, l.removed_by, l.removed_reason, l.shorter_stays, l.min_stay_months, l.bills_estimate_cents,
    u.username     AS owner_username,
    u.email        AS owner_email,
    u.avatar_url   AS owner_avatar_url,
    u.verified     AS owner_verified,
    u.suspended_at AS owner_suspended_at
FROM listings l
JOIN users u ON u.id = l.owner_id
WHERE ($1::text IS NULL
       OR l.search @@ websearch_to_tsquery('english', $1::text))
  AND ($2::text  IS NULL OR l.status = $2::text)
  AND ($3::bool IS NULL OR (l.removed_at IS NOT NULL) = $3::bool)
  AND ($4::uuid IS NULL OR l.owner_id = $4::uuid)
ORDER BY l.created_at DESC, l.id
LIMIT $6 OFFSET $5
`

type ListListingsForAdminParams struct {
	Search  *string
	Status  *string
	Removed *bool
	OwnerID *uuid.UUID
	Offset  int32
	Limit   int32
}

type ListListingsForAdminRow struct {
	Listing          Listing
	OwnerUsername    string
	OwnerEmail       string
	OwnerAvatarUrl   *string
	OwnerVerified    bool
	OwnerSuspendedAt *time.Time
}

// The operator's view of posts, and takedown.
//
// Takedown is not status. status is the owner's; removed_at is the
// moderator's. Restoring clears the moderator's columns and nothing else, so a
// restored post is back in whatever status its owner had left it, having never
// lost it.
// EVERY listing, in any status, removed or not, whoever owns it.
//
// This and ListRequestsForAdmin are the only queries in the repository that do
// not filter on status = 'published', suspension and takedown. The rest of the
// query files exist to keep that rule; these break it on purpose, because an
// operator has to see what the public cannot. Reached only through the /admin
// guard.
func (q *Queries) ListListingsForAdmin(ctx context.Context, arg ListListingsForAdminParams) ([]ListListingsForAdminRow, error) {
	rows, err := q.db.Query(ctx, listListingsForAdmin,
		arg.Search,
		arg.Status,
		arg.Removed,
		arg.OwnerID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListListingsForAdminRow{}
	for rows.Next() {
		var i ListListingsForAdminRow
		if err := rows.Scan(
			&i.Listing.ID,
			&i.Listing.OwnerID,
			&i.Listing.Title,
			&i.Listing.Body,
			&i.Listing.Conditions,
			&i.Listing.PriceCents,
			&i.Listing.DepositCents,
			&i.Listing.StartDate,
			&i.Listing.EndDate,
			&i.Listing.LeaseMonths,
			&i.Listing.TermTag,
			&i.Listing.UnitType,
			&i.Listing.BedroomsTotal,
			&i.Listing.BedroomOf,
			&i.Listing.Bathrooms,
			&i.Listing.BathType,
			&i.Listing.Furnished,
			&i.Listing.Utilities,
			&i.Listing.Parking,
			&i.Listing.Pets,
			&i.Listing.Laundry,
			&i.Listing.AddressLine,
			&i.Listing.Neighbourhood,
			&i.Listing.Lat,
			&i.Listing.Lng,
			&i.Listing.DistanceM,
			&i.Listing.CommuteMinutes,
			&i.Listing.CommuteMode,
			&i.Listing.MinutesToTransit,
			&i.Listing.MinutesToGrocery,
			&i.Listing.Status,
			&i.Listing.Views,
			&i.Listing.Replies,
			&i.Listing.Saves,
			&i.Listing.CreatedAt,
			&i.Listing.UpdatedAt,
			&i.Listing.Search,
			&i.Listing.PublishedAt,
			&i.Listing.RemovedAt,
			&i.Listing.RemovedBy,
			&i.Listing.RemovedReason,
			&i.Listing.ShorterStays,
			&i.Listing.MinStayMonths,
			&i.Listing.BillsEstimateCents,
			&i.OwnerUsername,
			&i.OwnerEmail,
			&i.OwnerAvatarUrl,
			&i.OwnerVerified,
			&i.OwnerSuspendedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsForAdmin = `-- name: ListRequestsForAdmin :many
SELECT
    r.id, r.poster_id, r.title, r.body, r.budget_cents, r.start_date, r.end_date, r.lease_months, r.term_tag, r.occupants, r.pets, r.furnished_preferred, r.parking_needed, r.laundry_needed, r.max_distance_m, r.neighbourhood, r.status, r.published_at, r.views, r.created_at, r.updated_at, r.search, r.removed_at, r.removed_by, r.removed_reason,
    u.username     AS poster_username,
    u.email        AS poster_email,
    u.avatar_url   AS poster_avatar_url,
    u.verified     AS poster_verified,
    u.suspended_at AS poster_suspended_at,
    (SELECT count(*)
       FROM request_offers o
       JOIN listings ol ON ol.id = o.listing_id
       JOIN users ou    ON ou.id = o.owner_id
      WHERE o.request_id = r.id
        AND o.withdrawn_at IS NULL
        AND ol.status = 'published'
        AND ol.removed_at IS NULL
        AND ou.suspended_at IS NULL) AS offer_count
FROM housing_requests r
JOIN users u ON u.id = r.poster_id
WHERE ($1::text IS NULL
       OR r.search @@ websearch_to_tsquery('english', $1::text))
  AND ($2::text  IS NULL OR r.status = $2::text)
  AND ($3::bool IS NULL OR (r.removed_at IS NOT NULL) = $3::bool)
  AND ($4::uuid IS NULL OR r.poster_id = $4::uuid)
ORDER BY r.created_at DESC, r.id
LIMIT $6 OFFSET $5
`

type ListRequestsForAdminParams struct {
	Search  *string
	Status  *string
	Removed *bool
	OwnerID *uuid.UUID
	Offset  int32
	Limit   int32
}

type ListRequestsForAdminRow struct {
	HousingRequest    HousingRequest
	PosterUsername    string
	PosterEmail       string
	PosterAvatarUrl   *string
	PosterVerified    bool
	PosterSuspendedAt *time.Time
	OfferCount        int64
}

// EVERY request, in any status, removed or not. The same deliberate exception
// as ListListingsForAdmin; see there. The offer count is the one the poster
// sees: live offers on visible listings from active owners.
func (q *Queries) ListRequestsForAdmin(ctx context.Context, arg ListRequestsForAdminParams) ([]ListRequestsForAdminRow, error) {
	rows, err := q.db.Query(ctx, listRequestsForAdmin,
		arg.Search,
		arg.Status,
		arg.Removed,
		arg.OwnerID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestsForAdminRow{}
	for rows.Next() {
		var i ListRequestsForAdminRow
		if err := rows.Scan(
			&i.HousingRequest.ID,
			&i.HousingRequest.PosterID,
			&i.HousingRequest.Title,
			&i.HousingRequest.Body,
			&i.HousingRequest.BudgetCents,
			&i.HousingRequest.StartDate,
			&i.HousingRequest.EndDate,
			&i.HousingRequest.LeaseMonths,
			&i.HousingRequest.TermTag,
			&i.HousingRequest.Occupants,
			&i.HousingRequest.Pets,
			&i.HousingRequest.FurnishedPreferred,
			&i.HousingRequest.ParkingNeeded,
			&i.HousingRequest.LaundryNeeded,
			&i.HousingRequest.MaxDistanceM,
			&i.HousingRequest.Neighbourhood,
			&i.HousingRequest.Status,
			&i.HousingRequest.PublishedAt,
			&i.HousingRequest.Views,
			&i.HousingRequest.CreatedAt,
			&i.HousingRequest.UpdatedAt,
			&i.HousingRequest.Search,
			&i.HousingRequest.RemovedAt,
			&i.HousingRequest.RemovedBy,
			&i.HousingRequest.RemovedReason,
			&i.PosterUsername,
			&i.PosterEmail,
			&i.PosterAvatarUrl,
			&i.PosterVerified,
			&i.PosterSuspendedAt,
			&i.OfferCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeListing = `-- name: RemoveListing :one
UPDATE listings
SET removed_at = now(), removed_by = $1, removed_reason = $2
WHERE id = $3 AND removed_at IS NULL
RETURNING id, owner_id, title, body, conditions, price_cents, deposit_cents, start_date, end_date, lease_months, term_tag, unit_type, bedrooms_total, bedroom_of, bathrooms, bath_type, furnished, utilities, parking, pets, laundry, address_line, neighbourhood, lat, lng, distance_m, commute_minutes, commute_mode, minutes_to_transit, minutes_to_grocery, status, views, replies, saves, created_at, updated_at, search, published_at, removed_at, removed_by, removed_reason, shorter_stays, min_stay_months, bills_estimate_cents
`

type RemoveListingParams struct {
	ActorID *uuid.UUID
	Reason  *string
	ID      uuid.UUID
}

// Takedown. Only a post not already removed matches, so a second takedown
// cannot overwrite the first one's time and reason; no row back means that.
func (q *Queries) RemoveListing(ctx context.Context, arg RemoveListingParams) (Listing, error) {
	row := q.db.QueryRow(ctx, removeListing, arg.ActorID, arg.Reason, arg.ID)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Body,
		&i.Conditions,
		&i.PriceCents,
		&i.DepositCents,
		&i.StartDate,
		&i.EndDate,
		&i.LeaseMonths,
		&i.TermTag,
		&i.UnitType,
		&i.BedroomsTotal,
		&i.BedroomOf,
		&i.Bathrooms,
		&i.BathType,
		&i.Furnished,
		&i.Utilities,
		&i.Parking,
		&i.Pets,
		&i.Laundry,
		&i.AddressLine,
		&i.Neighbourhood,
		&i.Lat,
		&i.Lng,
		&i.DistanceM,
		&i.CommuteMinutes,
		&i.CommuteMode,
		&i.MinutesToTransit,
		&i.MinutesToGrocery,
		&i.Status,
		&i.Views,
		&i.Replies,
		&i.Saves,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Search,
		&i.PublishedAt,
		&i.RemovedAt,
		&i.RemovedBy,
		&i.RemovedReason,
		&i.ShorterStays,
		&i.MinStayMonths,
		&i.BillsEstimateCents,
	)
	return i, err
}

const removeRequest = `-- name: RemoveRequest :one
UPDATE housing_requests
SET removed_at = now(), removed_by = $1, removed_reason = $2
WHERE id = $3 AND removed_at IS NULL
RETURNING id, poster_id, title, body, budget_cents, start_date, end_date, lease_months, term_tag, occupants, pets, furnished_preferred, parking_needed, laundry_needed, max_distance_m, neighbourhood, status, published_at, views, created_at, updated_at, search, removed_at, removed_by, removed_reason
`

type RemoveRequestParams struct {
	ActorID *uuid.UUID
	Reason  *string
	ID      uuid.UUID
}

func (q *Queries) RemoveRequest(ctx context.Context, arg RemoveRequestParams) (HousingRequest, error) {
	row := q.db.QueryRow(ctx, removeRequest, arg.ActorID, arg.Reason, arg.ID)
	var i HousingRequest
	err := row.Scan(
		&i.ID,
		&i.PosterID,
		&i.Title,
		&i.Body,
		&i.BudgetCents,
		&i.StartDate,
		&i.EndDate,
		&i.LeaseMonths,
		&i.TermTag,
		&i.Occupants,
		&i.Pets,
		&i.FurnishedPreferred,
		&i.ParkingNeeded,
		&i.LaundryNeeded,
		&i.MaxDistanceM,
		&i.Neighbourhood,
		&i.Status,
		&i.PublishedAt,
		&i.Views,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Search,
		&i.RemovedAt,
		&i.RemovedBy,
		&i.RemovedReason,
	)
	return i, err
}

const restoreListing = `-- name: RestoreListing :one
UPDATE listings
SET removed_at = NULL, removed_by = NULL, removed_reason = NULL
WHERE id = $1 AND removed_at IS NOT NULL
RETURNING id, owner_id, title, body, conditions, price_cents, deposit_cents, start_date, end_date, lease_months, term_tag, unit_type, bedrooms_total, bedroom_of, bathrooms, bath_type, furnished, utilities, parking, pets, laundry, address_line, neighbourhood, lat, lng, distance_m, commute_minutes, commute_mode, minutes_to_transit, minutes_to_grocery, status, views, replies, saves, created_at, updated_at, search, published_at, removed_at, removed_by, removed_reason, shorter_stays, min_stay_months, bills_estimate_cents
`

func (q *Queries) RestoreListing(ctx context.Context, id uuid.UUID) (Listing, error) {
	row := q.db.QueryRow(ctx, restoreListing, id)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Body,
		&i.Conditions,
		&i.PriceCents,
		&i.DepositCents,
		&i.StartDate,
		&i.EndDate,
		&i.LeaseMonths,
		&i.TermTag,
		&i.UnitType,
		&i.BedroomsTotal,
		&i.BedroomOf,
		&i.Bathrooms,
		&i.BathType,
		&i.Furnished,
		&i.Utilities,
		&i.Parking,
		&i.Pets,
		&i.Laundry,
		&i.AddressLine,
		&i.Neighbourhood,
		&i.Lat,
		&i.Lng,
		&i.DistanceM,
		&i.CommuteMinutes,
		&i.CommuteMode,
		&i.MinutesToTransit,
		&i.MinutesToGrocery,
		&i.Status,
		&i.Views,
		&i.Replies,
		&i.Saves,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Search,
		&i.PublishedAt,
		&i.RemovedAt,
		&i.RemovedBy,
		&i.RemovedReason,
		&i.ShorterStays,
		&i.MinStayMonths,
		&i.BillsEstimateCents,
	)
	return i, err
}

const restoreRequest = `-- name: RestoreRequest :one
UPDATE housing_requests
SET removed_at = NULL, removed_by = NULL, removed_reason = NULL
WHERE id = $1 AND removed_at IS NOT NULL
RETURNING id, poster_id, title, body, budget_cents, start_date, end_date, lease_months, term_tag, occupants, pets, furnished_preferred, parking_needed, laundry_needed, max_distance_m, neighbourhood, status, published_at, views, created_at, updated_at, search, removed_at, removed_by, removed_reason
`

func (q *Queries) RestoreRequest(ctx context.Context, id uuid.UUID) (HousingRequest, error) {
	row := q.db.QueryRow(ctx, restoreRequest, id)
	var i HousingRequest
	err := row.Scan(
		&i.ID,
		&i.PosterID,
		&i.Title,
		&i.Body,
		&i.BudgetCents,
		&i.StartDate,
		&i.EndDate,
		&i.LeaseMonths,
		&i.TermTag,
		&i.Occupants,
		&i.Pets,
		&i.FurnishedPreferred,
		&i.ParkingNeeded,
		&i.LaundryNeeded,
		&i.MaxDistanceM,
		&i.Neighbourhood,
		&i.Status,
		&i.PublishedAt,
		&i.Views,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Search,
		&i.RemovedAt,
		&i.RemovedBy,
		&i.RemovedReason,
	)
	return i, err
}
