// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adminOverviewCounts = `-- name: AdminOverviewCounts :one
SELECT
    (SELECT count(*) FROM users)                                  AS users_total,
    (SELECT count(*) FROM users WHERE verified)                   AS users_verified,
    (SELECT count(*) FROM users WHERE suspended_at IS NOT NULL)   AS users_suspended,
    (SELECT count(*) FROM users WHERE role = 'admin')             AS users_admin,
    (SELECT count(*) FROM listings)                               AS listings_total,
    (SELECT count(*) FROM listings WHERE status = 'published')    AS listings_published,
    (SELECT count(*) FROM housing_requests)                       AS requests_total,
    (SELECT count(*) FROM housing_requests WHERE status = 'published') AS requests_published,
    (SELECT count(*) FROM admin_actions
      WHERE created_at > now() - interval '7 days')               AS actions_last_week
`

type AdminOverviewCountsRow struct {
	UsersTotal        int64
	UsersVerified     int64
	UsersSuspended    int64
	UsersAdmin        int64
	ListingsTotal     int64
	ListingsPublished int64
	RequestsTotal     int64
	RequestsPublished int64
	ActionsLastWeek   int64
}

// The overview's numbers, in one round trip. Post counts include every status,
// with published broken out, because "how much is live" and "how much exists"
// are both questions an operator asks.
func (q *Queries) AdminOverviewCounts(ctx context.Context) (AdminOverviewCountsRow, error) {
	row := q.db.QueryRow(ctx, adminOverviewCounts)
	var i AdminOverviewCountsRow
	err := row.Scan(
		&i.UsersTotal,
		&i.UsersVerified,
		&i.UsersSuspended,
		&i.UsersAdmin,
		&i.ListingsTotal,
		&i.ListingsPublished,
		&i.RequestsTotal,
		&i.RequestsPublished,
		&i.ActionsLastWeek,
	)
	return i, err
}

const countAdminActions = `-- name: CountAdminActions :one
SELECT count(*) FROM admin_actions
`

func (q *Queries) CountAdminActions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminActions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdmins = `-- name: CountAdmins :one
SELECT count(*) FROM users WHERE role = 'admin'
`

// The last-admin guard reads this before any demotion.
func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersForAdmin = `-- name: CountUsersForAdmin :one
SELECT count(*)
FROM users u
WHERE ($1::text IS NULL
       OR u.email    ILIKE '%' || $1::text || '%'
       OR u.username ILIKE '%' || $1::text || '%')
  AND ($2::text     IS NULL OR u.role = $2::text)
  AND ($3::bool IS NULL OR u.verified = $3::bool)
  AND ($4::bool IS NULL
       OR (u.suspended_at IS NOT NULL) = $4::bool)
`

type CountUsersForAdminParams struct {
	Search    *string
	Role      *string
	Verified  *bool
	Suspended *bool
}

// The same filters, counted, so the page total describes the whole match.
func (q *Queries) CountUsersForAdmin(ctx context.Context, arg CountUsersForAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersForAdmin,
		arg.Search,
		arg.Role,
		arg.Verified,
		arg.Suspended,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserForAdmin = `-- name: GetUserForAdmin :one
SELECT
    u.id, u.email, u.username, u.role, u.verified, u.created_at,
    u.suspended_at, u.suspend_reason,
    (SELECT count(*) FROM listings l         WHERE l.owner_id  = u.id) AS listing_count,
    (SELECT count(*) FROM housing_requests r WHERE r.poster_id = u.id) AS request_count,
    (SELECT count(*) FROM request_offers o   WHERE o.owner_id  = u.id) AS offer_count
FROM users u
WHERE u.id = $1
`

type GetUserForAdminRow struct {
	ID            uuid.UUID
	Email         string
	Username      string
	Role          string
	Verified      bool
	CreatedAt     time.Time
	SuspendedAt   *time.Time
	SuspendReason *string
	ListingCount  int64
	RequestCount  int64
	OfferCount    int64
}

// One account, with what it has posted. Counts include every status: an
// operator needs to know about the draft as much as the published listing.
func (q *Queries) GetUserForAdmin(ctx context.Context, id uuid.UUID) (GetUserForAdminRow, error) {
	row := q.db.QueryRow(ctx, getUserForAdmin, id)
	var i GetUserForAdminRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Role,
		&i.Verified,
		&i.CreatedAt,
		&i.SuspendedAt,
		&i.SuspendReason,
		&i.ListingCount,
		&i.RequestCount,
		&i.OfferCount,
	)
	return i, err
}

const insertAdminAction = `-- name: InsertAdminAction :one
INSERT INTO admin_actions (actor_id, action, subject_type, subject_id, reason, detail)
VALUES (
    $1, $2, $3,
    $4, $5, $6
)
RETURNING id, actor_id, action, subject_type, subject_id, reason, detail, created_at
`

type InsertAdminActionParams struct {
	ActorID     *uuid.UUID
	Action      string
	SubjectType string
	SubjectID   uuid.UUID
	Reason      string
	Detail      []byte
}

// The only write against admin_actions.
func (q *Queries) InsertAdminAction(ctx context.Context, arg InsertAdminActionParams) (AdminAction, error) {
	row := q.db.QueryRow(ctx, insertAdminAction,
		arg.ActorID,
		arg.Action,
		arg.SubjectType,
		arg.SubjectID,
		arg.Reason,
		arg.Detail,
	)
	var i AdminAction
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Action,
		&i.SubjectType,
		&i.SubjectID,
		&i.Reason,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}

const listAdminActions = `-- name: ListAdminActions :many
SELECT
    a.id, a.actor_id, a.action, a.subject_type, a.subject_id, a.reason, a.detail, a.created_at,
    u.username AS actor_username
FROM admin_actions a
LEFT JOIN users u ON u.id = a.actor_id
ORDER BY a.created_at DESC, a.id
LIMIT $2 OFFSET $1
`

type ListAdminActionsParams struct {
	Offset int32
	Limit  int32
}

type ListAdminActionsRow struct {
	AdminAction   AdminAction
	ActorUsername *string
}

// The ledger, newest first, with the actor's name. A null actor is the host.
func (q *Queries) ListAdminActions(ctx context.Context, arg ListAdminActionsParams) ([]ListAdminActionsRow, error) {
	rows, err := q.db.Query(ctx, listAdminActions, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminActionsRow{}
	for rows.Next() {
		var i ListAdminActionsRow
		if err := rows.Scan(
			&i.AdminAction.ID,
			&i.AdminAction.ActorID,
			&i.AdminAction.Action,
			&i.AdminAction.SubjectType,
			&i.AdminAction.SubjectID,
			&i.AdminAction.Reason,
			&i.AdminAction.Detail,
			&i.AdminAction.CreatedAt,
			&i.ActorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminActionsForSubject = `-- name: ListAdminActionsForSubject :many
SELECT
    a.id, a.actor_id, a.action, a.subject_type, a.subject_id, a.reason, a.detail, a.created_at,
    u.username AS actor_username
FROM admin_actions a
LEFT JOIN users u ON u.id = a.actor_id
WHERE a.subject_type = $1 AND a.subject_id = $2
ORDER BY a.created_at DESC, a.id
`

type ListAdminActionsForSubjectParams struct {
	SubjectType string
	SubjectID   uuid.UUID
}

type ListAdminActionsForSubjectRow struct {
	AdminAction   AdminAction
	ActorUsername *string
}

// What has been done to one account or post, newest first.
func (q *Queries) ListAdminActionsForSubject(ctx context.Context, arg ListAdminActionsForSubjectParams) ([]ListAdminActionsForSubjectRow, error) {
	rows, err := q.db.Query(ctx, listAdminActionsForSubject, arg.SubjectType, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminActionsForSubjectRow{}
	for rows.Next() {
		var i ListAdminActionsForSubjectRow
		if err := rows.Scan(
			&i.AdminAction.ID,
			&i.AdminAction.ActorID,
			&i.AdminAction.Action,
			&i.AdminAction.SubjectType,
			&i.AdminAction.SubjectID,
			&i.AdminAction.Reason,
			&i.AdminAction.Detail,
			&i.AdminAction.CreatedAt,
			&i.ActorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersForAdmin = `-- name: ListUsersForAdmin :many

SELECT
    u.id, u.email, u.username, u.role, u.verified, u.created_at,
    u.suspended_at, u.suspend_reason,
    (SELECT count(*) FROM listings l         WHERE l.owner_id  = u.id) AS listing_count,
    (SELECT count(*) FROM housing_requests r WHERE r.poster_id = u.id) AS request_count,
    (SELECT count(*) FROM request_offers o   WHERE o.owner_id  = u.id) AS offer_count
FROM users u
WHERE ($1::text IS NULL
       OR u.email    ILIKE '%' || $1::text || '%'
       OR u.username ILIKE '%' || $1::text || '%')
  AND ($2::text     IS NULL OR u.role = $2::text)
  AND ($3::bool IS NULL OR u.verified = $3::bool)
  AND ($4::bool IS NULL
       OR (u.suspended_at IS NOT NULL) = $4::bool)
ORDER BY u.created_at DESC, u.id
LIMIT $6 OFFSET $5
`

type ListUsersForAdminParams struct {
	Search    *string
	Role      *string
	Verified  *bool
	Suspended *bool
	Offset    int32
	Limit     int32
}

type ListUsersForAdminRow struct {
	ID            uuid.UUID
	Email         string
	Username      string
	Role          string
	Verified      bool
	CreatedAt     time.Time
	SuspendedAt   *time.Time
	SuspendReason *string
	ListingCount  int64
	RequestCount  int64
	OfferCount    int64
}

// The operator's read surface, and the ledger.
//
// Everything here is reached only through the /admin guard or cmd/admin. These
// are the one set of queries allowed past the status = 'published' filter the
// public reads carry, because an operator has to see what the public cannot.
//
// admin_actions is append-only: there is an INSERT below and no UPDATE or
// DELETE anywhere in this directory. A test in internal/httpapi fails if one is
// added.
// Accounts, filtered and paged, newest first. Search matches a fragment of the
// email or the username, because an operator looking someone up has whichever
// one the complaint quoted, and often only part of it.
func (q *Queries) ListUsersForAdmin(ctx context.Context, arg ListUsersForAdminParams) ([]ListUsersForAdminRow, error) {
	rows, err := q.db.Query(ctx, listUsersForAdmin,
		arg.Search,
		arg.Role,
		arg.Verified,
		arg.Suspended,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersForAdminRow{}
	for rows.Next() {
		var i ListUsersForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.Role,
			&i.Verified,
			&i.CreatedAt,
			&i.SuspendedAt,
			&i.SuspendReason,
			&i.ListingCount,
			&i.RequestCount,
			&i.OfferCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserRole = `-- name: SetUserRole :one
UPDATE users SET role = $1 WHERE id = $2 RETURNING id, email, username, password_hash, role, verified, avatar_url, level, star_points, created_at, updated_at, suspended_at, suspended_by, suspend_reason
`

type SetUserRoleParams struct {
	Role string
	ID   uuid.UUID
}

// A role change. Only cmd/admin calls it in this phase; the portal gains it in
// Phase 10. Always paired with InsertAdminAction in one transaction.
func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserRole, arg.Role, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Verified,
		&i.AvatarUrl,
		&i.Level,
		&i.StarPoints,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuspendedAt,
		&i.SuspendedBy,
		&i.SuspendReason,
	)
	return i, err
}
