// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package sqlcgen

import (
	"context"
)

const ping = `-- name: Ping :one

SELECT 1::int AS ok
`

// Health check. Trivial on purpose: it exists to prove the whole chain — pool,
// sqlc codegen, generated method, real round-trip — works end to end, before any
// domain table exists to query.
func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
