// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listings.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countListings = `-- name: CountListings :one
SELECT count(*)
FROM listings l
JOIN users u ON u.id = l.owner_id
WHERE l.status = 'published'
  AND ($1::text IS NULL
       OR l.search @@ websearch_to_tsquery('english', $1::text))
  AND ($2::date  IS NULL OR l.start_date <= $2::date)
  AND ($3::date   IS NULL OR l.end_date   >= $3::date)
  AND ($4::int     IS NULL OR l.price_cents >= $4::int)
  AND ($5::int     IS NULL OR l.price_cents <= $5::int)
  AND ($6::int  IS NULL OR l.distance_m <= $6::int)
  AND ($7::int  IS NULL OR l.bedrooms_total >= $7::int)
  AND ($8::bool    IS NULL OR l.furnished = $8::bool)
  AND ($9::bool      IS NULL OR l.parking   = $9::bool)
  AND ($10::bool         IS NULL OR l.pets      = $10::bool)
  AND ($11::bool      IS NULL OR l.laundry   = $11::bool)
  AND ($12::text[]  IS NULL OR l.utilities @> $12::text[])
  AND ($13::bool IS NULL
       OR $13::bool = false
       OR u.verified = true)
`

type CountListingsParams struct {
	Search       *string
	StartAfter   *time.Time
	EndBefore    *time.Time
	PriceMin     *int32
	PriceMax     *int32
	DistanceMax  *int32
	BedroomsMin  *int32
	Furnished    *bool
	Parking      *bool
	Pets         *bool
	Laundry      *bool
	Utilities    []string
	VerifiedOnly *bool
}

func (q *Queries) CountListings(ctx context.Context, arg CountListingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countListings,
		arg.Search,
		arg.StartAfter,
		arg.EndBefore,
		arg.PriceMin,
		arg.PriceMax,
		arg.DistanceMax,
		arg.BedroomsMin,
		arg.Furnished,
		arg.Parking,
		arg.Pets,
		arg.Laundry,
		arg.Utilities,
		arg.VerifiedOnly,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createListing = `-- name: CreateListing :one
INSERT INTO listings (
    owner_id, title, body, conditions,
    price_cents, deposit_cents,
    start_date, end_date, lease_months, term_tag,
    unit_type, bedrooms_total, bedroom_of, bathrooms, bath_type,
    furnished, utilities, parking, pets, laundry,
    address_line, neighbourhood, lat, lng, distance_m,
    commute_minutes, commute_mode, minutes_to_transit, minutes_to_grocery,
    status, views, replies, created_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13, $14, $15,
    $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25,
    $26, $27, $28, $29,
    $30, $31, $32, $33
)
RETURNING id, owner_id, title, body, conditions, price_cents, deposit_cents, start_date, end_date, lease_months, term_tag, unit_type, bedrooms_total, bedroom_of, bathrooms, bath_type, furnished, utilities, parking, pets, laundry, address_line, neighbourhood, lat, lng, distance_m, commute_minutes, commute_mode, minutes_to_transit, minutes_to_grocery, status, views, replies, saves, created_at, updated_at, search, published_at
`

type CreateListingParams struct {
	OwnerID          uuid.UUID
	Title            string
	Body             string
	Conditions       []string
	PriceCents       int32
	DepositCents     *int32
	StartDate        time.Time
	EndDate          time.Time
	LeaseMonths      int32
	TermTag          string
	UnitType         string
	BedroomsTotal    int32
	BedroomOf        *int32
	Bathrooms        float64
	BathType         string
	Furnished        bool
	Utilities        []string
	Parking          bool
	Pets             bool
	Laundry          bool
	AddressLine      string
	Neighbourhood    string
	Lat              *float64
	Lng              *float64
	DistanceM        *int32
	CommuteMinutes   *int32
	CommuteMode      string
	MinutesToTransit *int32
	MinutesToGrocery *int32
	Status           string
	Views            int32
	Replies          int32
	CreatedAt        time.Time
}

func (q *Queries) CreateListing(ctx context.Context, arg CreateListingParams) (Listing, error) {
	row := q.db.QueryRow(ctx, createListing,
		arg.OwnerID,
		arg.Title,
		arg.Body,
		arg.Conditions,
		arg.PriceCents,
		arg.DepositCents,
		arg.StartDate,
		arg.EndDate,
		arg.LeaseMonths,
		arg.TermTag,
		arg.UnitType,
		arg.BedroomsTotal,
		arg.BedroomOf,
		arg.Bathrooms,
		arg.BathType,
		arg.Furnished,
		arg.Utilities,
		arg.Parking,
		arg.Pets,
		arg.Laundry,
		arg.AddressLine,
		arg.Neighbourhood,
		arg.Lat,
		arg.Lng,
		arg.DistanceM,
		arg.CommuteMinutes,
		arg.CommuteMode,
		arg.MinutesToTransit,
		arg.MinutesToGrocery,
		arg.Status,
		arg.Views,
		arg.Replies,
		arg.CreatedAt,
	)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Body,
		&i.Conditions,
		&i.PriceCents,
		&i.DepositCents,
		&i.StartDate,
		&i.EndDate,
		&i.LeaseMonths,
		&i.TermTag,
		&i.UnitType,
		&i.BedroomsTotal,
		&i.BedroomOf,
		&i.Bathrooms,
		&i.BathType,
		&i.Furnished,
		&i.Utilities,
		&i.Parking,
		&i.Pets,
		&i.Laundry,
		&i.AddressLine,
		&i.Neighbourhood,
		&i.Lat,
		&i.Lng,
		&i.DistanceM,
		&i.CommuteMinutes,
		&i.CommuteMode,
		&i.MinutesToTransit,
		&i.MinutesToGrocery,
		&i.Status,
		&i.Views,
		&i.Replies,
		&i.Saves,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Search,
		&i.PublishedAt,
	)
	return i, err
}

const deleteAllListings = `-- name: DeleteAllListings :exec
DELETE FROM listings
`

func (q *Queries) DeleteAllListings(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllListings)
	return err
}

const getListingForOwner = `-- name: GetListingForOwner :one
SELECT id, owner_id, title, body, conditions, price_cents, deposit_cents, start_date, end_date, lease_months, term_tag, unit_type, bedrooms_total, bedroom_of, bathrooms, bath_type, furnished, utilities, parking, pets, laundry, address_line, neighbourhood, lat, lng, distance_m, commute_minutes, commute_mode, minutes_to_transit, minutes_to_grocery, status, views, replies, saves, created_at, updated_at, search, published_at FROM listings WHERE id = $1
`

// Fetch for an ownership check. Returns the row whatever its status, so a
// handler can tell "not yours" from "does not exist" — and then deliberately
// answer 404 for both.
func (q *Queries) GetListingForOwner(ctx context.Context, id uuid.UUID) (Listing, error) {
	row := q.db.QueryRow(ctx, getListingForOwner, id)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Body,
		&i.Conditions,
		&i.PriceCents,
		&i.DepositCents,
		&i.StartDate,
		&i.EndDate,
		&i.LeaseMonths,
		&i.TermTag,
		&i.UnitType,
		&i.BedroomsTotal,
		&i.BedroomOf,
		&i.Bathrooms,
		&i.BathType,
		&i.Furnished,
		&i.Utilities,
		&i.Parking,
		&i.Pets,
		&i.Laundry,
		&i.AddressLine,
		&i.Neighbourhood,
		&i.Lat,
		&i.Lng,
		&i.DistanceM,
		&i.CommuteMinutes,
		&i.CommuteMode,
		&i.MinutesToTransit,
		&i.MinutesToGrocery,
		&i.Status,
		&i.Views,
		&i.Replies,
		&i.Saves,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Search,
		&i.PublishedAt,
	)
	return i, err
}

const getPublishedListing = `-- name: GetPublishedListing :one
SELECT
    l.id, l.owner_id, l.title, l.body, l.conditions, l.price_cents, l.deposit_cents, l.start_date, l.end_date, l.lease_months, l.term_tag, l.unit_type, l.bedrooms_total, l.bedroom_of, l.bathrooms, l.bath_type, l.furnished, l.utilities, l.parking, l.pets, l.laundry, l.address_line, l.neighbourhood, l.lat, l.lng, l.distance_m, l.commute_minutes, l.commute_mode, l.minutes_to_transit, l.minutes_to_grocery, l.status, l.views, l.replies, l.saves, l.created_at, l.updated_at, l.search, l.published_at,
    u.username    AS owner_username,
    u.avatar_url  AS owner_avatar_url,
    u.verified    AS owner_verified
FROM listings l
JOIN users u ON u.id = l.owner_id
WHERE l.id = $1 AND l.status = 'published'
`

type GetPublishedListingRow struct {
	Listing        Listing
	OwnerUsername  string
	OwnerAvatarUrl *string
	OwnerVerified  bool
}

func (q *Queries) GetPublishedListing(ctx context.Context, id uuid.UUID) (GetPublishedListingRow, error) {
	row := q.db.QueryRow(ctx, getPublishedListing, id)
	var i GetPublishedListingRow
	err := row.Scan(
		&i.Listing.ID,
		&i.Listing.OwnerID,
		&i.Listing.Title,
		&i.Listing.Body,
		&i.Listing.Conditions,
		&i.Listing.PriceCents,
		&i.Listing.DepositCents,
		&i.Listing.StartDate,
		&i.Listing.EndDate,
		&i.Listing.LeaseMonths,
		&i.Listing.TermTag,
		&i.Listing.UnitType,
		&i.Listing.BedroomsTotal,
		&i.Listing.BedroomOf,
		&i.Listing.Bathrooms,
		&i.Listing.BathType,
		&i.Listing.Furnished,
		&i.Listing.Utilities,
		&i.Listing.Parking,
		&i.Listing.Pets,
		&i.Listing.Laundry,
		&i.Listing.AddressLine,
		&i.Listing.Neighbourhood,
		&i.Listing.Lat,
		&i.Listing.Lng,
		&i.Listing.DistanceM,
		&i.Listing.CommuteMinutes,
		&i.Listing.CommuteMode,
		&i.Listing.MinutesToTransit,
		&i.Listing.MinutesToGrocery,
		&i.Listing.Status,
		&i.Listing.Views,
		&i.Listing.Replies,
		&i.Listing.Saves,
		&i.Listing.CreatedAt,
		&i.Listing.UpdatedAt,
		&i.Listing.Search,
		&i.Listing.PublishedAt,
		&i.OwnerUsername,
		&i.OwnerAvatarUrl,
		&i.OwnerVerified,
	)
	return i, err
}

const listListings = `-- name: ListListings :many


SELECT
    l.id, l.owner_id, l.title, l.body, l.conditions, l.price_cents, l.deposit_cents, l.start_date, l.end_date, l.lease_months, l.term_tag, l.unit_type, l.bedrooms_total, l.bedroom_of, l.bathrooms, l.bath_type, l.furnished, l.utilities, l.parking, l.pets, l.laundry, l.address_line, l.neighbourhood, l.lat, l.lng, l.distance_m, l.commute_minutes, l.commute_mode, l.minutes_to_transit, l.minutes_to_grocery, l.status, l.views, l.replies, l.saves, l.created_at, l.updated_at, l.search, l.published_at,
    u.username    AS owner_username,
    u.avatar_url  AS owner_avatar_url,
    u.verified    AS owner_verified
FROM listings l
JOIN users u ON u.id = l.owner_id
WHERE l.status = 'published'
  AND ($1::text IS NULL
       OR l.search @@ websearch_to_tsquery('english', $1::text))
  -- A listing is available for a wanted window if it starts by then and runs
  -- to at least the end of it.
  AND ($2::date  IS NULL OR l.start_date <= $2::date)
  AND ($3::date   IS NULL OR l.end_date   >= $3::date)
  AND ($4::int     IS NULL OR l.price_cents >= $4::int)
  AND ($5::int     IS NULL OR l.price_cents <= $5::int)
  -- A listing with no recorded distance is excluded when a limit is asked for:
  -- "within 2 km" cannot honestly include "distance unknown".
  AND ($6::int  IS NULL OR l.distance_m <= $6::int)
  AND ($7::int  IS NULL OR l.bedrooms_total >= $7::int)
  AND ($8::bool    IS NULL OR l.furnished = $8::bool)
  AND ($9::bool      IS NULL OR l.parking   = $9::bool)
  AND ($10::bool         IS NULL OR l.pets      = $10::bool)
  AND ($11::bool      IS NULL OR l.laundry   = $11::bool)
  -- Every requested utility must be included, not just one of them.
  AND ($12::text[]  IS NULL OR l.utilities @> $12::text[])
  AND ($13::bool IS NULL
       OR $13::bool = false
       OR u.verified = true)
ORDER BY
    CASE WHEN $14::text = 'priceAsc'  THEN l.price_cents END ASC,
    CASE WHEN $14::text = 'priceDesc' THEN l.price_cents END DESC,
    -- NULLS LAST: a listing with no distance should not lead a distance sort.
    CASE WHEN $14::text = 'distance'  THEN l.distance_m END ASC NULLS LAST,
    -- 'new' and 'match' both fall through to newest first. Real match scoring
    -- needs the viewer's own request, which does not exist yet.
    l.created_at DESC
LIMIT $16 OFFSET $15
`

type ListListingsParams struct {
	Search       *string
	StartAfter   *time.Time
	EndBefore    *time.Time
	PriceMin     *int32
	PriceMax     *int32
	DistanceMax  *int32
	BedroomsMin  *int32
	Furnished    *bool
	Parking      *bool
	Pets         *bool
	Laundry      *bool
	Utilities    []string
	VerifiedOnly *bool
	Sort         string
	Offset       int32
	Limit        int32
}

type ListListingsRow struct {
	Listing        Listing
	OwnerUsername  string
	OwnerAvatarUrl *string
	OwnerVerified  bool
}

// Only published rows are ever served. Filtering here rather than in Go means a
// handler cannot forget and expose somebody's draft.
// Filtered browse. Every parameter is optional and they compose: the
// "@param IS NULL OR ..." shape means one prepared statement serves every
// combination, with no string building anywhere near user input.
//
// Only published rows are ever returned, and that stays here in the SQL so a
// handler cannot forget it.
func (q *Queries) ListListings(ctx context.Context, arg ListListingsParams) ([]ListListingsRow, error) {
	rows, err := q.db.Query(ctx, listListings,
		arg.Search,
		arg.StartAfter,
		arg.EndBefore,
		arg.PriceMin,
		arg.PriceMax,
		arg.DistanceMax,
		arg.BedroomsMin,
		arg.Furnished,
		arg.Parking,
		arg.Pets,
		arg.Laundry,
		arg.Utilities,
		arg.VerifiedOnly,
		arg.Sort,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListListingsRow{}
	for rows.Next() {
		var i ListListingsRow
		if err := rows.Scan(
			&i.Listing.ID,
			&i.Listing.OwnerID,
			&i.Listing.Title,
			&i.Listing.Body,
			&i.Listing.Conditions,
			&i.Listing.PriceCents,
			&i.Listing.DepositCents,
			&i.Listing.StartDate,
			&i.Listing.EndDate,
			&i.Listing.LeaseMonths,
			&i.Listing.TermTag,
			&i.Listing.UnitType,
			&i.Listing.BedroomsTotal,
			&i.Listing.BedroomOf,
			&i.Listing.Bathrooms,
			&i.Listing.BathType,
			&i.Listing.Furnished,
			&i.Listing.Utilities,
			&i.Listing.Parking,
			&i.Listing.Pets,
			&i.Listing.Laundry,
			&i.Listing.AddressLine,
			&i.Listing.Neighbourhood,
			&i.Listing.Lat,
			&i.Listing.Lng,
			&i.Listing.DistanceM,
			&i.Listing.CommuteMinutes,
			&i.Listing.CommuteMode,
			&i.Listing.MinutesToTransit,
			&i.Listing.MinutesToGrocery,
			&i.Listing.Status,
			&i.Listing.Views,
			&i.Listing.Replies,
			&i.Listing.Saves,
			&i.Listing.CreatedAt,
			&i.Listing.UpdatedAt,
			&i.Listing.Search,
			&i.Listing.PublishedAt,
			&i.OwnerUsername,
			&i.OwnerAvatarUrl,
			&i.OwnerVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListingsByOwner = `-- name: ListListingsByOwner :many

SELECT
    l.id, l.owner_id, l.title, l.body, l.conditions, l.price_cents, l.deposit_cents, l.start_date, l.end_date, l.lease_months, l.term_tag, l.unit_type, l.bedrooms_total, l.bedroom_of, l.bathrooms, l.bath_type, l.furnished, l.utilities, l.parking, l.pets, l.laundry, l.address_line, l.neighbourhood, l.lat, l.lng, l.distance_m, l.commute_minutes, l.commute_mode, l.minutes_to_transit, l.minutes_to_grocery, l.status, l.views, l.replies, l.saves, l.created_at, l.updated_at, l.search, l.published_at,
    u.username    AS owner_username,
    u.avatar_url  AS owner_avatar_url,
    u.verified    AS owner_verified
FROM listings l
JOIN users u ON u.id = l.owner_id
WHERE l.owner_id = $1
ORDER BY l.created_at DESC
`

type ListListingsByOwnerRow struct {
	Listing        Listing
	OwnerUsername  string
	OwnerAvatarUrl *string
	OwnerVerified  bool
}

// ---------------------------------------------------------------- write path
// The owner's own listings, every status. The public endpoints show only
// published rows, so this is the only way to see a paused or archived post.
func (q *Queries) ListListingsByOwner(ctx context.Context, ownerID uuid.UUID) ([]ListListingsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listListingsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListListingsByOwnerRow{}
	for rows.Next() {
		var i ListListingsByOwnerRow
		if err := rows.Scan(
			&i.Listing.ID,
			&i.Listing.OwnerID,
			&i.Listing.Title,
			&i.Listing.Body,
			&i.Listing.Conditions,
			&i.Listing.PriceCents,
			&i.Listing.DepositCents,
			&i.Listing.StartDate,
			&i.Listing.EndDate,
			&i.Listing.LeaseMonths,
			&i.Listing.TermTag,
			&i.Listing.UnitType,
			&i.Listing.BedroomsTotal,
			&i.Listing.BedroomOf,
			&i.Listing.Bathrooms,
			&i.Listing.BathType,
			&i.Listing.Furnished,
			&i.Listing.Utilities,
			&i.Listing.Parking,
			&i.Listing.Pets,
			&i.Listing.Laundry,
			&i.Listing.AddressLine,
			&i.Listing.Neighbourhood,
			&i.Listing.Lat,
			&i.Listing.Lng,
			&i.Listing.DistanceM,
			&i.Listing.CommuteMinutes,
			&i.Listing.CommuteMode,
			&i.Listing.MinutesToTransit,
			&i.Listing.MinutesToGrocery,
			&i.Listing.Status,
			&i.Listing.Views,
			&i.Listing.Replies,
			&i.Listing.Saves,
			&i.Listing.CreatedAt,
			&i.Listing.UpdatedAt,
			&i.Listing.Search,
			&i.Listing.PublishedAt,
			&i.OwnerUsername,
			&i.OwnerAvatarUrl,
			&i.OwnerVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotosForListing = `-- name: ListPhotosForListing :many
SELECT id, listing_id, url, position, created_at FROM listing_photos
WHERE listing_id = $1
ORDER BY position, created_at
`

func (q *Queries) ListPhotosForListing(ctx context.Context, listingID uuid.UUID) ([]ListingPhoto, error) {
	rows, err := q.db.Query(ctx, listPhotosForListing, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListingPhoto{}
	for rows.Next() {
		var i ListingPhoto
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.Url,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotosForListings = `-- name: ListPhotosForListings :many
SELECT id, listing_id, url, position, created_at FROM listing_photos
WHERE listing_id = ANY($1::uuid[])
ORDER BY listing_id, position, created_at
`

// Photos for a page of listings in one round-trip, rather than one query per
// listing. Nothing populates the table yet, but the shape is what the list
// endpoint needs the moment it does.
func (q *Queries) ListPhotosForListings(ctx context.Context, dollar_1 []uuid.UUID) ([]ListingPhoto, error) {
	rows, err := q.db.Query(ctx, listPhotosForListings, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListingPhoto{}
	for rows.Next() {
		var i ListingPhoto
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.Url,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setListingStatus = `-- name: SetListingStatus :one
UPDATE listings
SET status = $1::text,
    published_at = CASE
        WHEN $1::text = 'published' AND published_at IS NULL THEN now()
        ELSE published_at
    END
WHERE id = $2
RETURNING id, owner_id, title, body, conditions, price_cents, deposit_cents, start_date, end_date, lease_months, term_tag, unit_type, bedrooms_total, bedroom_of, bathrooms, bath_type, furnished, utilities, parking, pets, laundry, address_line, neighbourhood, lat, lng, distance_m, commute_minutes, commute_mode, minutes_to_transit, minutes_to_grocery, status, views, replies, saves, created_at, updated_at, search, published_at
`

type SetListingStatusParams struct {
	Status string
	ID     uuid.UUID
}

// published_at is set the first time a listing goes live and never moved, so
// re-publishing after a pause does not make an old post look new.
// Cast on both uses: referring to the same parameter as varchar in one place
// and ::text in another makes PostgreSQL refuse to deduce a type for it
// (SQLSTATE 42P08).
func (q *Queries) SetListingStatus(ctx context.Context, arg SetListingStatusParams) (Listing, error) {
	row := q.db.QueryRow(ctx, setListingStatus, arg.Status, arg.ID)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Body,
		&i.Conditions,
		&i.PriceCents,
		&i.DepositCents,
		&i.StartDate,
		&i.EndDate,
		&i.LeaseMonths,
		&i.TermTag,
		&i.UnitType,
		&i.BedroomsTotal,
		&i.BedroomOf,
		&i.Bathrooms,
		&i.BathType,
		&i.Furnished,
		&i.Utilities,
		&i.Parking,
		&i.Pets,
		&i.Laundry,
		&i.AddressLine,
		&i.Neighbourhood,
		&i.Lat,
		&i.Lng,
		&i.DistanceM,
		&i.CommuteMinutes,
		&i.CommuteMode,
		&i.MinutesToTransit,
		&i.MinutesToGrocery,
		&i.Status,
		&i.Views,
		&i.Replies,
		&i.Saves,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Search,
		&i.PublishedAt,
	)
	return i, err
}

const updateListing = `-- name: UpdateListing :one
UPDATE listings SET
    title          = coalesce($1,          title),
    body           = coalesce($2,           body),
    conditions     = coalesce($3,     conditions),
    price_cents    = coalesce($4,    price_cents),
    deposit_cents  = coalesce($5,  deposit_cents),
    start_date     = coalesce($6,     start_date),
    end_date       = coalesce($7,       end_date),
    lease_months   = coalesce($8,   lease_months),
    term_tag       = coalesce($9,       term_tag),
    unit_type      = coalesce($10,      unit_type),
    bedrooms_total = coalesce($11, bedrooms_total),
    bedroom_of     = coalesce($12,     bedroom_of),
    bathrooms      = coalesce($13,      bathrooms),
    bath_type      = coalesce($14,      bath_type),
    furnished      = coalesce($15,      furnished),
    utilities      = coalesce($16,      utilities),
    parking        = coalesce($17,        parking),
    pets           = coalesce($18,           pets),
    laundry        = coalesce($19,        laundry),
    address_line   = coalesce($20,   address_line),
    neighbourhood  = coalesce($21,  neighbourhood),
    distance_m     = coalesce($22,     distance_m)
WHERE id = $23
RETURNING id, owner_id, title, body, conditions, price_cents, deposit_cents, start_date, end_date, lease_months, term_tag, unit_type, bedrooms_total, bedroom_of, bathrooms, bath_type, furnished, utilities, parking, pets, laundry, address_line, neighbourhood, lat, lng, distance_m, commute_minutes, commute_mode, minutes_to_transit, minutes_to_grocery, status, views, replies, saves, created_at, updated_at, search, published_at
`

type UpdateListingParams struct {
	Title         *string
	Body          *string
	Conditions    []string
	PriceCents    *int32
	DepositCents  *int32
	StartDate     *time.Time
	EndDate       *time.Time
	LeaseMonths   *int32
	TermTag       *string
	UnitType      *string
	BedroomsTotal *int32
	BedroomOf     *int32
	Bathrooms     *float64
	BathType      *string
	Furnished     *bool
	Utilities     []string
	Parking       *bool
	Pets          *bool
	Laundry       *bool
	AddressLine   *string
	Neighbourhood *string
	DistanceM     *int32
	ID            uuid.UUID
}

// Every field is optional: an edit form sends what changed, and COALESCE leaves
// the rest alone. A PUT would make every omitted field a deletion.
func (q *Queries) UpdateListing(ctx context.Context, arg UpdateListingParams) (Listing, error) {
	row := q.db.QueryRow(ctx, updateListing,
		arg.Title,
		arg.Body,
		arg.Conditions,
		arg.PriceCents,
		arg.DepositCents,
		arg.StartDate,
		arg.EndDate,
		arg.LeaseMonths,
		arg.TermTag,
		arg.UnitType,
		arg.BedroomsTotal,
		arg.BedroomOf,
		arg.Bathrooms,
		arg.BathType,
		arg.Furnished,
		arg.Utilities,
		arg.Parking,
		arg.Pets,
		arg.Laundry,
		arg.AddressLine,
		arg.Neighbourhood,
		arg.DistanceM,
		arg.ID,
	)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Body,
		&i.Conditions,
		&i.PriceCents,
		&i.DepositCents,
		&i.StartDate,
		&i.EndDate,
		&i.LeaseMonths,
		&i.TermTag,
		&i.UnitType,
		&i.BedroomsTotal,
		&i.BedroomOf,
		&i.Bathrooms,
		&i.BathType,
		&i.Furnished,
		&i.Utilities,
		&i.Parking,
		&i.Pets,
		&i.Laundry,
		&i.AddressLine,
		&i.Neighbourhood,
		&i.Lat,
		&i.Lng,
		&i.DistanceM,
		&i.CommuteMinutes,
		&i.CommuteMode,
		&i.MinutesToTransit,
		&i.MinutesToGrocery,
		&i.Status,
		&i.Views,
		&i.Replies,
		&i.Saves,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Search,
		&i.PublishedAt,
	)
	return i, err
}
