// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listings.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countPublishedListings = `-- name: CountPublishedListings :one
SELECT count(*) FROM listings WHERE status = 'published'
`

func (q *Queries) CountPublishedListings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedListings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createListing = `-- name: CreateListing :one
INSERT INTO listings (
    owner_id, title, body, conditions,
    price_cents, deposit_cents,
    start_date, end_date, lease_months, term_tag,
    unit_type, bedrooms_total, bedroom_of, bathrooms, bath_type,
    furnished, utilities, parking, pets, laundry,
    address_line, neighbourhood, lat, lng, distance_m,
    commute_minutes, commute_mode, minutes_to_transit, minutes_to_grocery,
    status, views, replies, created_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13, $14, $15,
    $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25,
    $26, $27, $28, $29,
    $30, $31, $32, $33
)
RETURNING id, owner_id, title, body, conditions, price_cents, deposit_cents, start_date, end_date, lease_months, term_tag, unit_type, bedrooms_total, bedroom_of, bathrooms, bath_type, furnished, utilities, parking, pets, laundry, address_line, neighbourhood, lat, lng, distance_m, commute_minutes, commute_mode, minutes_to_transit, minutes_to_grocery, status, views, replies, saves, created_at, updated_at
`

type CreateListingParams struct {
	OwnerID          uuid.UUID
	Title            string
	Body             string
	Conditions       []string
	PriceCents       int32
	DepositCents     *int32
	StartDate        time.Time
	EndDate          time.Time
	LeaseMonths      int32
	TermTag          string
	UnitType         string
	BedroomsTotal    int32
	BedroomOf        *int32
	Bathrooms        float64
	BathType         string
	Furnished        bool
	Utilities        []string
	Parking          bool
	Pets             bool
	Laundry          bool
	AddressLine      string
	Neighbourhood    string
	Lat              *float64
	Lng              *float64
	DistanceM        *int32
	CommuteMinutes   *int32
	CommuteMode      string
	MinutesToTransit *int32
	MinutesToGrocery *int32
	Status           string
	Views            int32
	Replies          int32
	CreatedAt        time.Time
}

func (q *Queries) CreateListing(ctx context.Context, arg CreateListingParams) (Listing, error) {
	row := q.db.QueryRow(ctx, createListing,
		arg.OwnerID,
		arg.Title,
		arg.Body,
		arg.Conditions,
		arg.PriceCents,
		arg.DepositCents,
		arg.StartDate,
		arg.EndDate,
		arg.LeaseMonths,
		arg.TermTag,
		arg.UnitType,
		arg.BedroomsTotal,
		arg.BedroomOf,
		arg.Bathrooms,
		arg.BathType,
		arg.Furnished,
		arg.Utilities,
		arg.Parking,
		arg.Pets,
		arg.Laundry,
		arg.AddressLine,
		arg.Neighbourhood,
		arg.Lat,
		arg.Lng,
		arg.DistanceM,
		arg.CommuteMinutes,
		arg.CommuteMode,
		arg.MinutesToTransit,
		arg.MinutesToGrocery,
		arg.Status,
		arg.Views,
		arg.Replies,
		arg.CreatedAt,
	)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Body,
		&i.Conditions,
		&i.PriceCents,
		&i.DepositCents,
		&i.StartDate,
		&i.EndDate,
		&i.LeaseMonths,
		&i.TermTag,
		&i.UnitType,
		&i.BedroomsTotal,
		&i.BedroomOf,
		&i.Bathrooms,
		&i.BathType,
		&i.Furnished,
		&i.Utilities,
		&i.Parking,
		&i.Pets,
		&i.Laundry,
		&i.AddressLine,
		&i.Neighbourhood,
		&i.Lat,
		&i.Lng,
		&i.DistanceM,
		&i.CommuteMinutes,
		&i.CommuteMode,
		&i.MinutesToTransit,
		&i.MinutesToGrocery,
		&i.Status,
		&i.Views,
		&i.Replies,
		&i.Saves,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllListings = `-- name: DeleteAllListings :exec
DELETE FROM listings
`

func (q *Queries) DeleteAllListings(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllListings)
	return err
}

const getPublishedListing = `-- name: GetPublishedListing :one
SELECT
    l.id, l.owner_id, l.title, l.body, l.conditions, l.price_cents, l.deposit_cents, l.start_date, l.end_date, l.lease_months, l.term_tag, l.unit_type, l.bedrooms_total, l.bedroom_of, l.bathrooms, l.bath_type, l.furnished, l.utilities, l.parking, l.pets, l.laundry, l.address_line, l.neighbourhood, l.lat, l.lng, l.distance_m, l.commute_minutes, l.commute_mode, l.minutes_to_transit, l.minutes_to_grocery, l.status, l.views, l.replies, l.saves, l.created_at, l.updated_at,
    u.username    AS owner_username,
    u.avatar_url  AS owner_avatar_url,
    u.verified    AS owner_verified
FROM listings l
JOIN users u ON u.id = l.owner_id
WHERE l.id = $1 AND l.status = 'published'
`

type GetPublishedListingRow struct {
	Listing        Listing
	OwnerUsername  string
	OwnerAvatarUrl *string
	OwnerVerified  bool
}

func (q *Queries) GetPublishedListing(ctx context.Context, id uuid.UUID) (GetPublishedListingRow, error) {
	row := q.db.QueryRow(ctx, getPublishedListing, id)
	var i GetPublishedListingRow
	err := row.Scan(
		&i.Listing.ID,
		&i.Listing.OwnerID,
		&i.Listing.Title,
		&i.Listing.Body,
		&i.Listing.Conditions,
		&i.Listing.PriceCents,
		&i.Listing.DepositCents,
		&i.Listing.StartDate,
		&i.Listing.EndDate,
		&i.Listing.LeaseMonths,
		&i.Listing.TermTag,
		&i.Listing.UnitType,
		&i.Listing.BedroomsTotal,
		&i.Listing.BedroomOf,
		&i.Listing.Bathrooms,
		&i.Listing.BathType,
		&i.Listing.Furnished,
		&i.Listing.Utilities,
		&i.Listing.Parking,
		&i.Listing.Pets,
		&i.Listing.Laundry,
		&i.Listing.AddressLine,
		&i.Listing.Neighbourhood,
		&i.Listing.Lat,
		&i.Listing.Lng,
		&i.Listing.DistanceM,
		&i.Listing.CommuteMinutes,
		&i.Listing.CommuteMode,
		&i.Listing.MinutesToTransit,
		&i.Listing.MinutesToGrocery,
		&i.Listing.Status,
		&i.Listing.Views,
		&i.Listing.Replies,
		&i.Listing.Saves,
		&i.Listing.CreatedAt,
		&i.Listing.UpdatedAt,
		&i.OwnerUsername,
		&i.OwnerAvatarUrl,
		&i.OwnerVerified,
	)
	return i, err
}

const listPhotosForListing = `-- name: ListPhotosForListing :many
SELECT id, listing_id, url, position, created_at FROM listing_photos
WHERE listing_id = $1
ORDER BY position, created_at
`

func (q *Queries) ListPhotosForListing(ctx context.Context, listingID uuid.UUID) ([]ListingPhoto, error) {
	rows, err := q.db.Query(ctx, listPhotosForListing, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListingPhoto{}
	for rows.Next() {
		var i ListingPhoto
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.Url,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotosForListings = `-- name: ListPhotosForListings :many
SELECT id, listing_id, url, position, created_at FROM listing_photos
WHERE listing_id = ANY($1::uuid[])
ORDER BY listing_id, position, created_at
`

// Photos for a page of listings in one round-trip, rather than one query per
// listing. Nothing populates the table yet, but the shape is what the list
// endpoint needs the moment it does.
func (q *Queries) ListPhotosForListings(ctx context.Context, dollar_1 []uuid.UUID) ([]ListingPhoto, error) {
	rows, err := q.db.Query(ctx, listPhotosForListings, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListingPhoto{}
	for rows.Next() {
		var i ListingPhoto
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.Url,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedListings = `-- name: ListPublishedListings :many

SELECT
    l.id, l.owner_id, l.title, l.body, l.conditions, l.price_cents, l.deposit_cents, l.start_date, l.end_date, l.lease_months, l.term_tag, l.unit_type, l.bedrooms_total, l.bedroom_of, l.bathrooms, l.bath_type, l.furnished, l.utilities, l.parking, l.pets, l.laundry, l.address_line, l.neighbourhood, l.lat, l.lng, l.distance_m, l.commute_minutes, l.commute_mode, l.minutes_to_transit, l.minutes_to_grocery, l.status, l.views, l.replies, l.saves, l.created_at, l.updated_at,
    u.username    AS owner_username,
    u.avatar_url  AS owner_avatar_url,
    u.verified    AS owner_verified
FROM listings l
JOIN users u ON u.id = l.owner_id
WHERE l.status = 'published'
ORDER BY l.created_at DESC
LIMIT $1 OFFSET $2
`

type ListPublishedListingsParams struct {
	Limit  int32
	Offset int32
}

type ListPublishedListingsRow struct {
	Listing        Listing
	OwnerUsername  string
	OwnerAvatarUrl *string
	OwnerVerified  bool
}

// Only published rows are ever served. Filtering here rather than in Go means a
// handler cannot forget and expose somebody's draft.
func (q *Queries) ListPublishedListings(ctx context.Context, arg ListPublishedListingsParams) ([]ListPublishedListingsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedListings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedListingsRow{}
	for rows.Next() {
		var i ListPublishedListingsRow
		if err := rows.Scan(
			&i.Listing.ID,
			&i.Listing.OwnerID,
			&i.Listing.Title,
			&i.Listing.Body,
			&i.Listing.Conditions,
			&i.Listing.PriceCents,
			&i.Listing.DepositCents,
			&i.Listing.StartDate,
			&i.Listing.EndDate,
			&i.Listing.LeaseMonths,
			&i.Listing.TermTag,
			&i.Listing.UnitType,
			&i.Listing.BedroomsTotal,
			&i.Listing.BedroomOf,
			&i.Listing.Bathrooms,
			&i.Listing.BathType,
			&i.Listing.Furnished,
			&i.Listing.Utilities,
			&i.Listing.Parking,
			&i.Listing.Pets,
			&i.Listing.Laundry,
			&i.Listing.AddressLine,
			&i.Listing.Neighbourhood,
			&i.Listing.Lat,
			&i.Listing.Lng,
			&i.Listing.DistanceM,
			&i.Listing.CommuteMinutes,
			&i.Listing.CommuteMode,
			&i.Listing.MinutesToTransit,
			&i.Listing.MinutesToGrocery,
			&i.Listing.Status,
			&i.Listing.Views,
			&i.Listing.Replies,
			&i.Listing.Saves,
			&i.Listing.CreatedAt,
			&i.Listing.UpdatedAt,
			&i.OwnerUsername,
			&i.OwnerAvatarUrl,
			&i.OwnerVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
