// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type EmailVerificationToken struct {
	TokenHash  []byte
	UserID     uuid.UUID
	ExpiresAt  time.Time
	ConsumedAt *time.Time
	CreatedAt  time.Time
}

type Listing struct {
	ID               uuid.UUID
	OwnerID          uuid.UUID
	Title            string
	Body             string
	Conditions       []string
	PriceCents       int32
	DepositCents     *int32
	StartDate        time.Time
	EndDate          time.Time
	LeaseMonths      int32
	TermTag          string
	UnitType         string
	BedroomsTotal    int32
	BedroomOf        *int32
	Bathrooms        float64
	BathType         string
	Furnished        bool
	Utilities        []string
	Parking          bool
	Pets             bool
	Laundry          bool
	AddressLine      string
	Neighbourhood    string
	Lat              *float64
	Lng              *float64
	DistanceM        *int32
	CommuteMinutes   *int32
	CommuteMode      string
	MinutesToTransit *int32
	MinutesToGrocery *int32
	Status           string
	Views            int32
	Replies          int32
	Saves            int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Search           interface{}
	PublishedAt      *time.Time
}

type ListingPhoto struct {
	ID        uuid.UUID
	ListingID uuid.UUID
	Url       string
	Position  int32
	CreatedAt time.Time
}

type PasswordResetToken struct {
	TokenHash  []byte
	UserID     uuid.UUID
	ExpiresAt  time.Time
	ConsumedAt *time.Time
	CreatedAt  time.Time
}

type RefreshToken struct {
	TokenHash []byte
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt *time.Time
	UserAgent *string
	CreatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	Username     string
	PasswordHash string
	Role         string
	Verified     bool
	AvatarUrl    *string
	Level        int32
	StarPoints   int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
