// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: offers.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const countOffersForRequest = `-- name: CountOffersForRequest :one
SELECT count(*)
FROM request_offers o
JOIN listings l ON l.id = o.listing_id
WHERE o.request_id = $1
  AND o.withdrawn_at IS NULL
  AND l.status = 'published'
`

// The same count the read queries compute inline, for the write path's
// responses. Visible offers only, on the same two conditions.
func (q *Queries) CountOffersForRequest(ctx context.Context, requestID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOffersForRequest, requestID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOffer = `-- name: CreateOffer :one

INSERT INTO request_offers (request_id, listing_id, owner_id, note)
VALUES ($1, $2, $3, $4)
RETURNING id, request_id, listing_id, owner_id, note, withdrawn_at, created_at, updated_at
`

type CreateOfferParams struct {
	RequestID uuid.UUID
	ListingID uuid.UUID
	OwnerID   uuid.UUID
	Note      string
}

// An owner's answer to a request: one of their own listings, with an optional
// note.
//
// Visibility is not symmetric. The student who posted the request sees every
// live offer on it; an owner sees only their own. Owners reading each other's
// answers would turn a request into an auction.
func (q *Queries) CreateOffer(ctx context.Context, arg CreateOfferParams) (RequestOffer, error) {
	row := q.db.QueryRow(ctx, createOffer,
		arg.RequestID,
		arg.ListingID,
		arg.OwnerID,
		arg.Note,
	)
	var i RequestOffer
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ListingID,
		&i.OwnerID,
		&i.Note,
		&i.WithdrawnAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOffer = `-- name: GetOffer :one
SELECT id, request_id, listing_id, owner_id, note, withdrawn_at, created_at, updated_at FROM request_offers WHERE id = $1
`

// Any offer by id, for the ownership check before a withdrawal. "Not yours" and
// "does not exist" answer alike in the handler.
func (q *Queries) GetOffer(ctx context.Context, id uuid.UUID) (RequestOffer, error) {
	row := q.db.QueryRow(ctx, getOffer, id)
	var i RequestOffer
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ListingID,
		&i.OwnerID,
		&i.Note,
		&i.WithdrawnAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOfferForListing = `-- name: GetOfferForListing :one
SELECT id, request_id, listing_id, owner_id, note, withdrawn_at, created_at, updated_at FROM request_offers
WHERE request_id = $1 AND listing_id = $2
`

type GetOfferForListingParams struct {
	RequestID uuid.UUID
	ListingID uuid.UUID
}

// Whether this owner has already offered this listing here, withdrawn or not.
// The unique constraint is the real guarantee; this is so the handler can say
// so in words rather than returning a constraint violation.
func (q *Queries) GetOfferForListing(ctx context.Context, arg GetOfferForListingParams) (RequestOffer, error) {
	row := q.db.QueryRow(ctx, getOfferForListing, arg.RequestID, arg.ListingID)
	var i RequestOffer
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ListingID,
		&i.OwnerID,
		&i.Note,
		&i.WithdrawnAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOffersByOwner = `-- name: ListOffersByOwner :many
SELECT
    o.id, o.request_id, o.listing_id, o.owner_id, o.note, o.withdrawn_at, o.created_at, o.updated_at,
    l.id, l.owner_id, l.title, l.body, l.conditions, l.price_cents, l.deposit_cents, l.start_date, l.end_date, l.lease_months, l.term_tag, l.unit_type, l.bedrooms_total, l.bedroom_of, l.bathrooms, l.bath_type, l.furnished, l.utilities, l.parking, l.pets, l.laundry, l.address_line, l.neighbourhood, l.lat, l.lng, l.distance_m, l.commute_minutes, l.commute_mode, l.minutes_to_transit, l.minutes_to_grocery, l.status, l.views, l.replies, l.saves, l.created_at, l.updated_at, l.search, l.published_at
FROM request_offers o
JOIN listings l ON l.id = o.listing_id
WHERE o.owner_id = $1
ORDER BY o.created_at DESC
`

type ListOffersByOwnerRow struct {
	RequestOffer RequestOffer
	Listing      Listing
}

// An owner's own offers, whatever became of them.
func (q *Queries) ListOffersByOwner(ctx context.Context, ownerID uuid.UUID) ([]ListOffersByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listOffersByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOffersByOwnerRow{}
	for rows.Next() {
		var i ListOffersByOwnerRow
		if err := rows.Scan(
			&i.RequestOffer.ID,
			&i.RequestOffer.RequestID,
			&i.RequestOffer.ListingID,
			&i.RequestOffer.OwnerID,
			&i.RequestOffer.Note,
			&i.RequestOffer.WithdrawnAt,
			&i.RequestOffer.CreatedAt,
			&i.RequestOffer.UpdatedAt,
			&i.Listing.ID,
			&i.Listing.OwnerID,
			&i.Listing.Title,
			&i.Listing.Body,
			&i.Listing.Conditions,
			&i.Listing.PriceCents,
			&i.Listing.DepositCents,
			&i.Listing.StartDate,
			&i.Listing.EndDate,
			&i.Listing.LeaseMonths,
			&i.Listing.TermTag,
			&i.Listing.UnitType,
			&i.Listing.BedroomsTotal,
			&i.Listing.BedroomOf,
			&i.Listing.Bathrooms,
			&i.Listing.BathType,
			&i.Listing.Furnished,
			&i.Listing.Utilities,
			&i.Listing.Parking,
			&i.Listing.Pets,
			&i.Listing.Laundry,
			&i.Listing.AddressLine,
			&i.Listing.Neighbourhood,
			&i.Listing.Lat,
			&i.Listing.Lng,
			&i.Listing.DistanceM,
			&i.Listing.CommuteMinutes,
			&i.Listing.CommuteMode,
			&i.Listing.MinutesToTransit,
			&i.Listing.MinutesToGrocery,
			&i.Listing.Status,
			&i.Listing.Views,
			&i.Listing.Replies,
			&i.Listing.Saves,
			&i.Listing.CreatedAt,
			&i.Listing.UpdatedAt,
			&i.Listing.Search,
			&i.Listing.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOffersForRequest = `-- name: ListOffersForRequest :many
SELECT
    o.id, o.request_id, o.listing_id, o.owner_id, o.note, o.withdrawn_at, o.created_at, o.updated_at,
    l.id, l.owner_id, l.title, l.body, l.conditions, l.price_cents, l.deposit_cents, l.start_date, l.end_date, l.lease_months, l.term_tag, l.unit_type, l.bedrooms_total, l.bedroom_of, l.bathrooms, l.bath_type, l.furnished, l.utilities, l.parking, l.pets, l.laundry, l.address_line, l.neighbourhood, l.lat, l.lng, l.distance_m, l.commute_minutes, l.commute_mode, l.minutes_to_transit, l.minutes_to_grocery, l.status, l.views, l.replies, l.saves, l.created_at, l.updated_at, l.search, l.published_at,
    u.username   AS owner_username,
    u.avatar_url AS owner_avatar_url,
    u.verified   AS owner_verified
FROM request_offers o
JOIN listings l ON l.id = o.listing_id
JOIN users u    ON u.id = o.owner_id
WHERE o.request_id = $1
  AND o.withdrawn_at IS NULL
  AND l.status = 'published'
ORDER BY o.created_at DESC
`

type ListOffersForRequestRow struct {
	RequestOffer   RequestOffer
	Listing        Listing
	OwnerUsername  string
	OwnerAvatarUrl *string
	OwnerVerified  bool
}

// The offers on a request, as the student sees them: the listing comes with it,
// so the reply shows real rent and dates rather than a pitch.
//
// An offer is live only while its listing is: taking a listing down withdraws
// its offers, with nothing else to remember. Same for an explicit withdrawal.
func (q *Queries) ListOffersForRequest(ctx context.Context, requestID uuid.UUID) ([]ListOffersForRequestRow, error) {
	rows, err := q.db.Query(ctx, listOffersForRequest, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOffersForRequestRow{}
	for rows.Next() {
		var i ListOffersForRequestRow
		if err := rows.Scan(
			&i.RequestOffer.ID,
			&i.RequestOffer.RequestID,
			&i.RequestOffer.ListingID,
			&i.RequestOffer.OwnerID,
			&i.RequestOffer.Note,
			&i.RequestOffer.WithdrawnAt,
			&i.RequestOffer.CreatedAt,
			&i.RequestOffer.UpdatedAt,
			&i.Listing.ID,
			&i.Listing.OwnerID,
			&i.Listing.Title,
			&i.Listing.Body,
			&i.Listing.Conditions,
			&i.Listing.PriceCents,
			&i.Listing.DepositCents,
			&i.Listing.StartDate,
			&i.Listing.EndDate,
			&i.Listing.LeaseMonths,
			&i.Listing.TermTag,
			&i.Listing.UnitType,
			&i.Listing.BedroomsTotal,
			&i.Listing.BedroomOf,
			&i.Listing.Bathrooms,
			&i.Listing.BathType,
			&i.Listing.Furnished,
			&i.Listing.Utilities,
			&i.Listing.Parking,
			&i.Listing.Pets,
			&i.Listing.Laundry,
			&i.Listing.AddressLine,
			&i.Listing.Neighbourhood,
			&i.Listing.Lat,
			&i.Listing.Lng,
			&i.Listing.DistanceM,
			&i.Listing.CommuteMinutes,
			&i.Listing.CommuteMode,
			&i.Listing.MinutesToTransit,
			&i.Listing.MinutesToGrocery,
			&i.Listing.Status,
			&i.Listing.Views,
			&i.Listing.Replies,
			&i.Listing.Saves,
			&i.Listing.CreatedAt,
			&i.Listing.UpdatedAt,
			&i.Listing.Search,
			&i.Listing.PublishedAt,
			&i.OwnerUsername,
			&i.OwnerAvatarUrl,
			&i.OwnerVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const withdrawOffer = `-- name: WithdrawOffer :one
UPDATE request_offers
SET withdrawn_at = now()
WHERE id = $1 AND withdrawn_at IS NULL
RETURNING id, request_id, listing_id, owner_id, note, withdrawn_at, created_at, updated_at
`

// Withdrawn rather than deleted: the row stays, so the same listing cannot be
// re-offered against the same request by working around the unique constraint.
func (q *Queries) WithdrawOffer(ctx context.Context, id uuid.UUID) (RequestOffer, error) {
	row := q.db.QueryRow(ctx, withdrawOffer, id)
	var i RequestOffer
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ListingID,
		&i.OwnerID,
		&i.Note,
		&i.WithdrawnAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
