// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// A fresh request invalidates earlier outstanding ones, so a forwarded old email
	// cannot still be used.
	ConsumeAllEmailVerificationTokensForUser(ctx context.Context, userID uuid.UUID) error
	ConsumeAllPasswordResetTokensForUser(ctx context.Context, userID uuid.UUID) error
	ConsumeEmailVerificationToken(ctx context.Context, tokenHash []byte) error
	ConsumePasswordResetToken(ctx context.Context, tokenHash []byte) error
	CountListings(ctx context.Context, arg CountListingsParams) (int64, error)
	// The same count the read queries compute inline, for the write path's
	// responses. Visible offers only, on the same two conditions.
	CountOffersForRequest(ctx context.Context, requestID uuid.UUID) (int64, error)
	CountRequests(ctx context.Context, arg CountRequestsParams) (int64, error)
	// Used to tell a duplicate email from a duplicate username *internally*, without
	// the response revealing which one collided.
	CountUsersByEmailOrUsername(ctx context.Context, arg CountUsersByEmailOrUsernameParams) (CountUsersByEmailOrUsernameRow, error)
	// Every lookup here filters on consumed/revoked and expiry in SQL rather than in
	// Go, so a caller cannot forget the check and accept a spent token.
	CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) error
	CreateListing(ctx context.Context, arg CreateListingParams) (Listing, error)
	// An owner's answer to a request: one of their own listings, with an optional
	// note.
	//
	// Visibility is not symmetric. The student who posted the request sees every
	// live offer on it; an owner sees only their own. Owners reading each other's
	// answers would turn a request into an auction.
	CreateOffer(ctx context.Context, arg CreateOfferParams) (RequestOffer, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	// published_at is stamped here, on creation, when the request goes straight to
	// published. listings.published_at is only set by a later status change, which
	// leaves a listing created as published without one; that is not repeated.
	CreateRequest(ctx context.Context, arg CreateRequestParams) (HousingRequest, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllListings(ctx context.Context) error
	// What cmd/seed calls before reseeding.
	DeleteAllRequests(ctx context.Context) error
	DeleteExpiredTokens(ctx context.Context) error
	// Fetch for an ownership check. Returns the row whatever its status, so a
	// handler can tell "not yours" from "does not exist" — and then deliberately
	// answer 404 for both.
	GetListingForOwner(ctx context.Context, id uuid.UUID) (Listing, error)
	GetLiveEmailVerificationToken(ctx context.Context, tokenHash []byte) (EmailVerificationToken, error)
	GetLivePasswordResetToken(ctx context.Context, tokenHash []byte) (PasswordResetToken, error)
	GetLiveRefreshToken(ctx context.Context, tokenHash []byte) (RefreshToken, error)
	// Any offer by id, for the ownership check before a withdrawal. "Not yours" and
	// "does not exist" answer alike in the handler.
	GetOffer(ctx context.Context, id uuid.UUID) (RequestOffer, error)
	// Whether this owner has already offered this listing here, withdrawn or not.
	// The unique constraint is the real guarantee; this is so the handler can say
	// so in words rather than returning a constraint violation.
	GetOfferForListing(ctx context.Context, arg GetOfferForListingParams) (RequestOffer, error)
	GetPublishedListing(ctx context.Context, id uuid.UUID) (GetPublishedListingRow, error)
	GetPublishedRequest(ctx context.Context, id uuid.UUID) (GetPublishedRequestRow, error)
	// Any status, so ownership can be checked before an edit. "Not yours" and "does
	// not exist" answer alike in the handler.
	GetRequestForOwner(ctx context.Context, id uuid.UUID) (HousingRequest, error)
	// Addresses are compared case-insensitively, matching the unique index.
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, lower string) (User, error)
	// Only published rows are ever served. Filtering here rather than in Go means a
	// handler cannot forget and expose somebody's draft.
	// Filtered browse. Every parameter is optional and they compose: the
	// "@param IS NULL OR ..." shape means one prepared statement serves every
	// combination, with no string building anywhere near user input.
	//
	// Only published rows are ever returned, and that stays here in the SQL so a
	// handler cannot forget it.
	ListListings(ctx context.Context, arg ListListingsParams) ([]ListListingsRow, error)
	// ---------------------------------------------------------------- write path
	// The owner's own listings, every status. The public endpoints show only
	// published rows, so this is the only way to see a paused or archived post.
	ListListingsByOwner(ctx context.Context, ownerID uuid.UUID) ([]ListListingsByOwnerRow, error)
	// An owner's own offers, whatever became of them.
	ListOffersByOwner(ctx context.Context, ownerID uuid.UUID) ([]ListOffersByOwnerRow, error)
	// The offers on a request, as the student sees them: the listing comes with it,
	// so the reply shows real rent and dates rather than a pitch.
	//
	// An offer is live only while its listing is: taking a listing down withdraws
	// its offers, with nothing else to remember. Same for an explicit withdrawal.
	ListOffersForRequest(ctx context.Context, requestID uuid.UUID) ([]ListOffersForRequestRow, error)
	ListPhotosForListing(ctx context.Context, listingID uuid.UUID) ([]ListingPhoto, error)
	// Photos for a page of listings in one round-trip, rather than one query per
	// listing. Nothing populates the table yet, but the shape is what the list
	// endpoint needs the moment it does.
	ListPhotosForListings(ctx context.Context, dollar_1 []uuid.UUID) ([]ListingPhoto, error)
	// "Looking for Housing" posts. Only published rows are ever served, and that
	// stays here in the SQL so a handler cannot forget it.
	//
	// The filters read from the owner's side: a request's budget is a ceiling, so
	// "budget_min" asks who can afford at least this much, and its distance is a
	// radius, so "distance_max" asks who would accept a place this far out.
	// The offer count is computed, never stored. An offer stops counting when its
	// listing is taken down — which happens in another table — so any stored number
	// would drift from what the student can actually see.
	ListRequests(ctx context.Context, arg ListRequestsParams) ([]ListRequestsRow, error)
	// ---------------------------------------------------------------- write path
	// The poster's own requests, every status. The public endpoints show only
	// published ones, so this is the only way to see a draft or a paused request.
	ListRequestsByPoster(ctx context.Context, posterID uuid.UUID) ([]ListRequestsByPosterRow, error)
	MarkUserVerified(ctx context.Context, id uuid.UUID) (User, error)
	// Health check. Trivial on purpose: it exists to prove the whole chain — pool,
	// sqlc codegen, generated method, real round-trip — works end to end, before any
	// domain table exists to query.
	Ping(ctx context.Context) (int32, error)
	// Used on password change: every existing session is ended, so a password reset
	// actually evicts whoever prompted it.
	RevokeAllRefreshTokensForUser(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, tokenHash []byte) error
	// published_at is set the first time a listing goes live and never moved, so
	// re-publishing after a pause does not make an old post look new.
	// Cast on both uses: referring to the same parameter as varchar in one place
	// and ::text in another makes PostgreSQL refuse to deduce a type for it
	// (SQLSTATE 42P08).
	SetListingStatus(ctx context.Context, arg SetListingStatusParams) (Listing, error)
	// Cast on both uses of the parameter: referring to it as varchar in one place
	// and ::text in another makes PostgreSQL refuse to deduce a type (SQLSTATE
	// 42P08). That shipped once already on listings.
	SetRequestStatus(ctx context.Context, arg SetRequestStatusParams) (HousingRequest, error)
	// Every field is optional: an edit form sends what changed, and COALESCE leaves
	// the rest alone. A PUT would make every omitted field a deletion.
	UpdateListing(ctx context.Context, arg UpdateListingParams) (Listing, error)
	// A partial edit: anything not given keeps its current value. A PUT would make
	// every omitted field a deletion.
	UpdateRequest(ctx context.Context, arg UpdateRequestParams) (HousingRequest, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// Withdrawn rather than deleted: the row stays, so the same listing cannot be
	// re-offered against the same request by working around the unique constraint.
	WithdrawOffer(ctx context.Context, id uuid.UUID) (RequestOffer, error)
}

var _ Querier = (*Queries)(nil)
