// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// A fresh request invalidates earlier outstanding ones, so a forwarded old email
	// cannot still be used.
	ConsumeAllEmailVerificationTokensForUser(ctx context.Context, userID uuid.UUID) error
	ConsumeAllPasswordResetTokensForUser(ctx context.Context, userID uuid.UUID) error
	ConsumeEmailVerificationToken(ctx context.Context, tokenHash []byte) error
	ConsumePasswordResetToken(ctx context.Context, tokenHash []byte) error
	CountListings(ctx context.Context, arg CountListingsParams) (int64, error)
	// Used to tell a duplicate email from a duplicate username *internally*, without
	// the response revealing which one collided.
	CountUsersByEmailOrUsername(ctx context.Context, arg CountUsersByEmailOrUsernameParams) (CountUsersByEmailOrUsernameRow, error)
	// Every lookup here filters on consumed/revoked and expiry in SQL rather than in
	// Go, so a caller cannot forget the check and accept a spent token.
	CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) error
	CreateListing(ctx context.Context, arg CreateListingParams) (Listing, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllListings(ctx context.Context) error
	DeleteExpiredTokens(ctx context.Context) error
	// Fetch for an ownership check. Returns the row whatever its status, so a
	// handler can tell "not yours" from "does not exist" — and then deliberately
	// answer 404 for both.
	GetListingForOwner(ctx context.Context, id uuid.UUID) (Listing, error)
	GetLiveEmailVerificationToken(ctx context.Context, tokenHash []byte) (EmailVerificationToken, error)
	GetLivePasswordResetToken(ctx context.Context, tokenHash []byte) (PasswordResetToken, error)
	GetLiveRefreshToken(ctx context.Context, tokenHash []byte) (RefreshToken, error)
	GetPublishedListing(ctx context.Context, id uuid.UUID) (GetPublishedListingRow, error)
	// Addresses are compared case-insensitively, matching the unique index.
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, lower string) (User, error)
	// Only published rows are ever served. Filtering here rather than in Go means a
	// handler cannot forget and expose somebody's draft.
	// Filtered browse. Every parameter is optional and they compose: the
	// "@param IS NULL OR ..." shape means one prepared statement serves every
	// combination, with no string building anywhere near user input.
	//
	// Only published rows are ever returned, and that stays here in the SQL so a
	// handler cannot forget it.
	ListListings(ctx context.Context, arg ListListingsParams) ([]ListListingsRow, error)
	// ---------------------------------------------------------------- write path
	// The owner's own listings, every status. The public endpoints show only
	// published rows, so this is the only way to see a paused or archived post.
	ListListingsByOwner(ctx context.Context, ownerID uuid.UUID) ([]ListListingsByOwnerRow, error)
	ListPhotosForListing(ctx context.Context, listingID uuid.UUID) ([]ListingPhoto, error)
	// Photos for a page of listings in one round-trip, rather than one query per
	// listing. Nothing populates the table yet, but the shape is what the list
	// endpoint needs the moment it does.
	ListPhotosForListings(ctx context.Context, dollar_1 []uuid.UUID) ([]ListingPhoto, error)
	MarkUserVerified(ctx context.Context, id uuid.UUID) (User, error)
	// Health check. Trivial on purpose: it exists to prove the whole chain — pool,
	// sqlc codegen, generated method, real round-trip — works end to end, before any
	// domain table exists to query.
	Ping(ctx context.Context) (int32, error)
	// Used on password change: every existing session is ended, so a password reset
	// actually evicts whoever prompted it.
	RevokeAllRefreshTokensForUser(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, tokenHash []byte) error
	// published_at is set the first time a listing goes live and never moved, so
	// re-publishing after a pause does not make an old post look new.
	// Cast on both uses: referring to the same parameter as varchar in one place
	// and ::text in another makes PostgreSQL refuse to deduce a type for it
	// (SQLSTATE 42P08).
	SetListingStatus(ctx context.Context, arg SetListingStatusParams) (Listing, error)
	// Every field is optional: an edit form sends what changed, and COALESCE leaves
	// the rest alone. A PUT would make every omitted field a deletion.
	UpdateListing(ctx context.Context, arg UpdateListingParams) (Listing, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
