// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countRequests = `-- name: CountRequests :one
SELECT count(*)
FROM housing_requests r
JOIN users u ON u.id = r.poster_id
WHERE r.status = 'published'
  AND ($1::text IS NULL
       OR r.search @@ websearch_to_tsquery('english', $1::text))
  AND ($2::date IS NULL OR r.start_date <= $2::date)
  AND ($3::date  IS NULL OR r.end_date   >= $3::date)
  AND ($4::int    IS NULL OR r.budget_cents >= $4::int)
  AND ($5::int    IS NULL OR r.budget_cents <= $5::int)
  AND ($6::int  IS NULL
       OR r.max_distance_m IS NULL
       OR r.max_distance_m >= $6::int)
  AND ($7::int IS NULL OR r.occupants <= $7::int)
  AND ($8::bool         IS NULL OR r.pets = $8::bool)
  AND ($9::bool    IS NULL OR r.furnished_preferred = $9::bool)
  AND ($10::bool      IS NULL OR r.parking_needed = $10::bool)
  AND ($11::bool      IS NULL OR r.laundry_needed = $11::bool)
  AND ($12::bool IS NULL
       OR $12::bool = false
       OR u.verified = true)
`

type CountRequestsParams struct {
	Search       *string
	StartAfter   *time.Time
	EndBefore    *time.Time
	BudgetMin    *int32
	BudgetMax    *int32
	DistanceMin  *int32
	OccupantsMax *int32
	Pets         *bool
	Furnished    *bool
	Parking      *bool
	Laundry      *bool
	VerifiedOnly *bool
}

func (q *Queries) CountRequests(ctx context.Context, arg CountRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRequests,
		arg.Search,
		arg.StartAfter,
		arg.EndBefore,
		arg.BudgetMin,
		arg.BudgetMax,
		arg.DistanceMin,
		arg.OccupantsMax,
		arg.Pets,
		arg.Furnished,
		arg.Parking,
		arg.Laundry,
		arg.VerifiedOnly,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRequest = `-- name: CreateRequest :one
INSERT INTO housing_requests (
    poster_id, title, body,
    budget_cents,
    start_date, end_date, lease_months, term_tag,
    occupants, pets, furnished_preferred, parking_needed, laundry_needed,
    max_distance_m, neighbourhood,
    views,
    status, published_at, created_at
) VALUES (
    $1, $2, $3,
    $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12, $13,
    $14, $15,
    -- Only the seed sets this; a real request starts at zero.
    $16,
    $17::text,
    CASE WHEN $17::text = 'published' THEN now() END,
    $18
)
RETURNING id, poster_id, title, body, budget_cents, start_date, end_date, lease_months, term_tag, occupants, pets, furnished_preferred, parking_needed, laundry_needed, max_distance_m, neighbourhood, status, published_at, views, offers, created_at, updated_at, search
`

type CreateRequestParams struct {
	PosterID           uuid.UUID
	Title              string
	Body               string
	BudgetCents        int32
	StartDate          time.Time
	EndDate            time.Time
	LeaseMonths        int32
	TermTag            string
	Occupants          int32
	Pets               bool
	FurnishedPreferred bool
	ParkingNeeded      bool
	LaundryNeeded      bool
	MaxDistanceM       *int32
	Neighbourhood      string
	Views              int32
	Status             string
	CreatedAt          time.Time
}

// published_at is stamped here, on creation, when the request goes straight to
// published. listings.published_at is only set by a later status change, which
// leaves a listing created as published without one; that is not repeated.
func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (HousingRequest, error) {
	row := q.db.QueryRow(ctx, createRequest,
		arg.PosterID,
		arg.Title,
		arg.Body,
		arg.BudgetCents,
		arg.StartDate,
		arg.EndDate,
		arg.LeaseMonths,
		arg.TermTag,
		arg.Occupants,
		arg.Pets,
		arg.FurnishedPreferred,
		arg.ParkingNeeded,
		arg.LaundryNeeded,
		arg.MaxDistanceM,
		arg.Neighbourhood,
		arg.Views,
		arg.Status,
		arg.CreatedAt,
	)
	var i HousingRequest
	err := row.Scan(
		&i.ID,
		&i.PosterID,
		&i.Title,
		&i.Body,
		&i.BudgetCents,
		&i.StartDate,
		&i.EndDate,
		&i.LeaseMonths,
		&i.TermTag,
		&i.Occupants,
		&i.Pets,
		&i.FurnishedPreferred,
		&i.ParkingNeeded,
		&i.LaundryNeeded,
		&i.MaxDistanceM,
		&i.Neighbourhood,
		&i.Status,
		&i.PublishedAt,
		&i.Views,
		&i.Offers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Search,
	)
	return i, err
}

const deleteAllRequests = `-- name: DeleteAllRequests :exec
DELETE FROM housing_requests
`

// What cmd/seed calls before reseeding.
func (q *Queries) DeleteAllRequests(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllRequests)
	return err
}

const getPublishedRequest = `-- name: GetPublishedRequest :one
SELECT
    r.id, r.poster_id, r.title, r.body, r.budget_cents, r.start_date, r.end_date, r.lease_months, r.term_tag, r.occupants, r.pets, r.furnished_preferred, r.parking_needed, r.laundry_needed, r.max_distance_m, r.neighbourhood, r.status, r.published_at, r.views, r.offers, r.created_at, r.updated_at, r.search,
    u.username   AS poster_username,
    u.avatar_url AS poster_avatar_url,
    u.verified   AS poster_verified
FROM housing_requests r
JOIN users u ON u.id = r.poster_id
WHERE r.id = $1 AND r.status = 'published'
`

type GetPublishedRequestRow struct {
	HousingRequest  HousingRequest
	PosterUsername  string
	PosterAvatarUrl *string
	PosterVerified  bool
}

func (q *Queries) GetPublishedRequest(ctx context.Context, id uuid.UUID) (GetPublishedRequestRow, error) {
	row := q.db.QueryRow(ctx, getPublishedRequest, id)
	var i GetPublishedRequestRow
	err := row.Scan(
		&i.HousingRequest.ID,
		&i.HousingRequest.PosterID,
		&i.HousingRequest.Title,
		&i.HousingRequest.Body,
		&i.HousingRequest.BudgetCents,
		&i.HousingRequest.StartDate,
		&i.HousingRequest.EndDate,
		&i.HousingRequest.LeaseMonths,
		&i.HousingRequest.TermTag,
		&i.HousingRequest.Occupants,
		&i.HousingRequest.Pets,
		&i.HousingRequest.FurnishedPreferred,
		&i.HousingRequest.ParkingNeeded,
		&i.HousingRequest.LaundryNeeded,
		&i.HousingRequest.MaxDistanceM,
		&i.HousingRequest.Neighbourhood,
		&i.HousingRequest.Status,
		&i.HousingRequest.PublishedAt,
		&i.HousingRequest.Views,
		&i.HousingRequest.Offers,
		&i.HousingRequest.CreatedAt,
		&i.HousingRequest.UpdatedAt,
		&i.HousingRequest.Search,
		&i.PosterUsername,
		&i.PosterAvatarUrl,
		&i.PosterVerified,
	)
	return i, err
}

const getRequestForOwner = `-- name: GetRequestForOwner :one
SELECT id, poster_id, title, body, budget_cents, start_date, end_date, lease_months, term_tag, occupants, pets, furnished_preferred, parking_needed, laundry_needed, max_distance_m, neighbourhood, status, published_at, views, offers, created_at, updated_at, search FROM housing_requests WHERE id = $1
`

// Any status, so ownership can be checked before an edit. "Not yours" and "does
// not exist" answer alike in the handler.
func (q *Queries) GetRequestForOwner(ctx context.Context, id uuid.UUID) (HousingRequest, error) {
	row := q.db.QueryRow(ctx, getRequestForOwner, id)
	var i HousingRequest
	err := row.Scan(
		&i.ID,
		&i.PosterID,
		&i.Title,
		&i.Body,
		&i.BudgetCents,
		&i.StartDate,
		&i.EndDate,
		&i.LeaseMonths,
		&i.TermTag,
		&i.Occupants,
		&i.Pets,
		&i.FurnishedPreferred,
		&i.ParkingNeeded,
		&i.LaundryNeeded,
		&i.MaxDistanceM,
		&i.Neighbourhood,
		&i.Status,
		&i.PublishedAt,
		&i.Views,
		&i.Offers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Search,
	)
	return i, err
}

const listRequests = `-- name: ListRequests :many

SELECT
    r.id, r.poster_id, r.title, r.body, r.budget_cents, r.start_date, r.end_date, r.lease_months, r.term_tag, r.occupants, r.pets, r.furnished_preferred, r.parking_needed, r.laundry_needed, r.max_distance_m, r.neighbourhood, r.status, r.published_at, r.views, r.offers, r.created_at, r.updated_at, r.search,
    u.username   AS poster_username,
    u.avatar_url AS poster_avatar_url,
    u.verified   AS poster_verified
FROM housing_requests r
JOIN users u ON u.id = r.poster_id
WHERE r.status = 'published'
  AND ($1::text IS NULL
       OR r.search @@ websearch_to_tsquery('english', $1::text))
  -- A request wants a place for its own window: it overlaps what an owner has
  -- if it starts by then and runs to at least the end of it.
  AND ($2::date IS NULL OR r.start_date <= $2::date)
  AND ($3::date  IS NULL OR r.end_date   >= $3::date)
  -- Budget is what they will pay at most, so an owner asking $900 wants
  -- budget_min = 90000: everyone whose ceiling reaches their rent.
  AND ($4::int    IS NULL OR r.budget_cents >= $4::int)
  AND ($5::int    IS NULL OR r.budget_cents <= $5::int)
  -- "Would this person consider a place this far out?" A request with no stated
  -- radius is included: no preference is not the same as a narrow one, which is
  -- the opposite of how a listing's unknown distance is treated.
  AND ($6::int  IS NULL
       OR r.max_distance_m IS NULL
       OR r.max_distance_m >= $6::int)
  AND ($7::int IS NULL OR r.occupants <= $7::int)
  AND ($8::bool         IS NULL OR r.pets = $8::bool)
  AND ($9::bool    IS NULL OR r.furnished_preferred = $9::bool)
  AND ($10::bool      IS NULL OR r.parking_needed = $10::bool)
  AND ($11::bool      IS NULL OR r.laundry_needed = $11::bool)
  AND ($12::bool IS NULL
       OR $12::bool = false
       OR u.verified = true)
ORDER BY
    CASE WHEN $13::text = 'budgetDesc' THEN r.budget_cents END DESC,
    CASE WHEN $13::text = 'budgetAsc'  THEN r.budget_cents END ASC,
    CASE WHEN $13::text = 'soonest'    THEN r.start_date END ASC,
    -- 'new' and 'match' both fall through to newest first, as on listings.
    r.created_at DESC
LIMIT $15 OFFSET $14
`

type ListRequestsParams struct {
	Search       *string
	StartAfter   *time.Time
	EndBefore    *time.Time
	BudgetMin    *int32
	BudgetMax    *int32
	DistanceMin  *int32
	OccupantsMax *int32
	Pets         *bool
	Furnished    *bool
	Parking      *bool
	Laundry      *bool
	VerifiedOnly *bool
	Sort         string
	Offset       int32
	Limit        int32
}

type ListRequestsRow struct {
	HousingRequest  HousingRequest
	PosterUsername  string
	PosterAvatarUrl *string
	PosterVerified  bool
}

// "Looking for Housing" posts. Only published rows are ever served, and that
// stays here in the SQL so a handler cannot forget it.
//
// The filters read from the owner's side: a request's budget is a ceiling, so
// "budget_min" asks who can afford at least this much, and its distance is a
// radius, so "distance_max" asks who would accept a place this far out.
func (q *Queries) ListRequests(ctx context.Context, arg ListRequestsParams) ([]ListRequestsRow, error) {
	rows, err := q.db.Query(ctx, listRequests,
		arg.Search,
		arg.StartAfter,
		arg.EndBefore,
		arg.BudgetMin,
		arg.BudgetMax,
		arg.DistanceMin,
		arg.OccupantsMax,
		arg.Pets,
		arg.Furnished,
		arg.Parking,
		arg.Laundry,
		arg.VerifiedOnly,
		arg.Sort,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestsRow{}
	for rows.Next() {
		var i ListRequestsRow
		if err := rows.Scan(
			&i.HousingRequest.ID,
			&i.HousingRequest.PosterID,
			&i.HousingRequest.Title,
			&i.HousingRequest.Body,
			&i.HousingRequest.BudgetCents,
			&i.HousingRequest.StartDate,
			&i.HousingRequest.EndDate,
			&i.HousingRequest.LeaseMonths,
			&i.HousingRequest.TermTag,
			&i.HousingRequest.Occupants,
			&i.HousingRequest.Pets,
			&i.HousingRequest.FurnishedPreferred,
			&i.HousingRequest.ParkingNeeded,
			&i.HousingRequest.LaundryNeeded,
			&i.HousingRequest.MaxDistanceM,
			&i.HousingRequest.Neighbourhood,
			&i.HousingRequest.Status,
			&i.HousingRequest.PublishedAt,
			&i.HousingRequest.Views,
			&i.HousingRequest.Offers,
			&i.HousingRequest.CreatedAt,
			&i.HousingRequest.UpdatedAt,
			&i.HousingRequest.Search,
			&i.PosterUsername,
			&i.PosterAvatarUrl,
			&i.PosterVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByPoster = `-- name: ListRequestsByPoster :many

SELECT
    r.id, r.poster_id, r.title, r.body, r.budget_cents, r.start_date, r.end_date, r.lease_months, r.term_tag, r.occupants, r.pets, r.furnished_preferred, r.parking_needed, r.laundry_needed, r.max_distance_m, r.neighbourhood, r.status, r.published_at, r.views, r.offers, r.created_at, r.updated_at, r.search,
    u.username   AS poster_username,
    u.avatar_url AS poster_avatar_url,
    u.verified   AS poster_verified
FROM housing_requests r
JOIN users u ON u.id = r.poster_id
WHERE r.poster_id = $1
ORDER BY r.created_at DESC
`

type ListRequestsByPosterRow struct {
	HousingRequest  HousingRequest
	PosterUsername  string
	PosterAvatarUrl *string
	PosterVerified  bool
}

// ---------------------------------------------------------------- write path
// The poster's own requests, every status. The public endpoints show only
// published ones, so this is the only way to see a draft or a paused request.
func (q *Queries) ListRequestsByPoster(ctx context.Context, posterID uuid.UUID) ([]ListRequestsByPosterRow, error) {
	rows, err := q.db.Query(ctx, listRequestsByPoster, posterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestsByPosterRow{}
	for rows.Next() {
		var i ListRequestsByPosterRow
		if err := rows.Scan(
			&i.HousingRequest.ID,
			&i.HousingRequest.PosterID,
			&i.HousingRequest.Title,
			&i.HousingRequest.Body,
			&i.HousingRequest.BudgetCents,
			&i.HousingRequest.StartDate,
			&i.HousingRequest.EndDate,
			&i.HousingRequest.LeaseMonths,
			&i.HousingRequest.TermTag,
			&i.HousingRequest.Occupants,
			&i.HousingRequest.Pets,
			&i.HousingRequest.FurnishedPreferred,
			&i.HousingRequest.ParkingNeeded,
			&i.HousingRequest.LaundryNeeded,
			&i.HousingRequest.MaxDistanceM,
			&i.HousingRequest.Neighbourhood,
			&i.HousingRequest.Status,
			&i.HousingRequest.PublishedAt,
			&i.HousingRequest.Views,
			&i.HousingRequest.Offers,
			&i.HousingRequest.CreatedAt,
			&i.HousingRequest.UpdatedAt,
			&i.HousingRequest.Search,
			&i.PosterUsername,
			&i.PosterAvatarUrl,
			&i.PosterVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRequestStatus = `-- name: SetRequestStatus :one
UPDATE housing_requests
SET status = $1::text,
    published_at = CASE
        WHEN $1::text = 'published' AND published_at IS NULL THEN now()
        ELSE published_at
    END
WHERE id = $2
RETURNING id, poster_id, title, body, budget_cents, start_date, end_date, lease_months, term_tag, occupants, pets, furnished_preferred, parking_needed, laundry_needed, max_distance_m, neighbourhood, status, published_at, views, offers, created_at, updated_at, search
`

type SetRequestStatusParams struct {
	Status string
	ID     uuid.UUID
}

// Cast on both uses of the parameter: referring to it as varchar in one place
// and ::text in another makes PostgreSQL refuse to deduce a type (SQLSTATE
// 42P08). That shipped once already on listings.
func (q *Queries) SetRequestStatus(ctx context.Context, arg SetRequestStatusParams) (HousingRequest, error) {
	row := q.db.QueryRow(ctx, setRequestStatus, arg.Status, arg.ID)
	var i HousingRequest
	err := row.Scan(
		&i.ID,
		&i.PosterID,
		&i.Title,
		&i.Body,
		&i.BudgetCents,
		&i.StartDate,
		&i.EndDate,
		&i.LeaseMonths,
		&i.TermTag,
		&i.Occupants,
		&i.Pets,
		&i.FurnishedPreferred,
		&i.ParkingNeeded,
		&i.LaundryNeeded,
		&i.MaxDistanceM,
		&i.Neighbourhood,
		&i.Status,
		&i.PublishedAt,
		&i.Views,
		&i.Offers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Search,
	)
	return i, err
}

const updateRequest = `-- name: UpdateRequest :one
UPDATE housing_requests
SET title               = coalesce($1,               title),
    body                = coalesce($2,                body),
    budget_cents        = coalesce($3,        budget_cents),
    start_date          = coalesce($4,          start_date),
    end_date            = coalesce($5,            end_date),
    lease_months        = coalesce($6,        lease_months),
    term_tag            = coalesce($7,            term_tag),
    occupants           = coalesce($8,           occupants),
    pets                = coalesce($9,                pets),
    furnished_preferred = coalesce($10, furnished_preferred),
    parking_needed      = coalesce($11,      parking_needed),
    laundry_needed      = coalesce($12,      laundry_needed),
    max_distance_m      = coalesce($13,      max_distance_m),
    neighbourhood       = coalesce($14,       neighbourhood)
WHERE id = $15
RETURNING id, poster_id, title, body, budget_cents, start_date, end_date, lease_months, term_tag, occupants, pets, furnished_preferred, parking_needed, laundry_needed, max_distance_m, neighbourhood, status, published_at, views, offers, created_at, updated_at, search
`

type UpdateRequestParams struct {
	Title              *string
	Body               *string
	BudgetCents        *int32
	StartDate          *time.Time
	EndDate            *time.Time
	LeaseMonths        *int32
	TermTag            *string
	Occupants          *int32
	Pets               *bool
	FurnishedPreferred *bool
	ParkingNeeded      *bool
	LaundryNeeded      *bool
	MaxDistanceM       *int32
	Neighbourhood      *string
	ID                 uuid.UUID
}

// A partial edit: anything not given keeps its current value. A PUT would make
// every omitted field a deletion.
func (q *Queries) UpdateRequest(ctx context.Context, arg UpdateRequestParams) (HousingRequest, error) {
	row := q.db.QueryRow(ctx, updateRequest,
		arg.Title,
		arg.Body,
		arg.BudgetCents,
		arg.StartDate,
		arg.EndDate,
		arg.LeaseMonths,
		arg.TermTag,
		arg.Occupants,
		arg.Pets,
		arg.FurnishedPreferred,
		arg.ParkingNeeded,
		arg.LaundryNeeded,
		arg.MaxDistanceM,
		arg.Neighbourhood,
		arg.ID,
	)
	var i HousingRequest
	err := row.Scan(
		&i.ID,
		&i.PosterID,
		&i.Title,
		&i.Body,
		&i.BudgetCents,
		&i.StartDate,
		&i.EndDate,
		&i.LeaseMonths,
		&i.TermTag,
		&i.Occupants,
		&i.Pets,
		&i.FurnishedPreferred,
		&i.ParkingNeeded,
		&i.LaundryNeeded,
		&i.MaxDistanceM,
		&i.Neighbourhood,
		&i.Status,
		&i.PublishedAt,
		&i.Views,
		&i.Offers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Search,
	)
	return i, err
}
