// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeAllEmailVerificationTokensForUser = `-- name: ConsumeAllEmailVerificationTokensForUser :exec
UPDATE email_verification_tokens SET consumed_at = now()
WHERE user_id = $1 AND consumed_at IS NULL
`

// A fresh request invalidates earlier outstanding ones, so a forwarded old email
// cannot still be used.
func (q *Queries) ConsumeAllEmailVerificationTokensForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeAllEmailVerificationTokensForUser, userID)
	return err
}

const consumeAllPasswordResetTokensForUser = `-- name: ConsumeAllPasswordResetTokensForUser :exec
UPDATE password_reset_tokens SET consumed_at = now()
WHERE user_id = $1 AND consumed_at IS NULL
`

func (q *Queries) ConsumeAllPasswordResetTokensForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeAllPasswordResetTokensForUser, userID)
	return err
}

const consumeEmailVerificationToken = `-- name: ConsumeEmailVerificationToken :exec
UPDATE email_verification_tokens SET consumed_at = now()
WHERE token_hash = $1 AND consumed_at IS NULL
`

func (q *Queries) ConsumeEmailVerificationToken(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, consumeEmailVerificationToken, tokenHash)
	return err
}

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :exec
UPDATE password_reset_tokens SET consumed_at = now()
WHERE token_hash = $1 AND consumed_at IS NULL
`

func (q *Queries) ConsumePasswordResetToken(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, consumePasswordResetToken, tokenHash)
	return err
}

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :exec

INSERT INTO email_verification_tokens (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateEmailVerificationTokenParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	ExpiresAt time.Time
}

// Every lookup here filters on consumed/revoked and expiry in SQL rather than in
// Go, so a caller cannot forget the check and accept a spent token.
func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, createEmailVerificationToken, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
INSERT INTO password_reset_tokens (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreatePasswordResetTokenParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, createPasswordResetToken, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (token_hash, user_id, expires_at, user_agent)
VALUES ($1, $2, $3, $4)
`

type CreateRefreshTokenParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	ExpiresAt time.Time
	UserAgent *string
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.TokenHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.UserAgent,
	)
	return err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
WITH deleted_refresh AS (
    DELETE FROM refresh_tokens WHERE expires_at < now()
), deleted_verification AS (
    DELETE FROM email_verification_tokens WHERE expires_at < now()
)
DELETE FROM password_reset_tokens WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTokens)
	return err
}

const getLiveEmailVerificationToken = `-- name: GetLiveEmailVerificationToken :one
SELECT token_hash, user_id, expires_at, consumed_at, created_at FROM email_verification_tokens
WHERE token_hash = $1 AND consumed_at IS NULL AND expires_at > now()
`

func (q *Queries) GetLiveEmailVerificationToken(ctx context.Context, tokenHash []byte) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getLiveEmailVerificationToken, tokenHash)
	var i EmailVerificationToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLivePasswordResetToken = `-- name: GetLivePasswordResetToken :one
SELECT token_hash, user_id, expires_at, consumed_at, created_at FROM password_reset_tokens
WHERE token_hash = $1 AND consumed_at IS NULL AND expires_at > now()
`

func (q *Queries) GetLivePasswordResetToken(ctx context.Context, tokenHash []byte) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getLivePasswordResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLiveRefreshToken = `-- name: GetLiveRefreshToken :one
SELECT token_hash, user_id, expires_at, revoked_at, user_agent, created_at FROM refresh_tokens
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) GetLiveRefreshToken(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getLiveRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllRefreshTokensForUser = `-- name: RevokeAllRefreshTokensForUser :exec
UPDATE refresh_tokens SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

// Used on password change: every existing session is ended, so a password reset
// actually evicts whoever prompted it.
func (q *Queries) RevokeAllRefreshTokensForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokensForUser, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}
