// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const countUsersByEmailOrUsername = `-- name: CountUsersByEmailOrUsername :one
SELECT
    count(*) FILTER (WHERE lower(email) = lower($1))    AS email_count,
    count(*) FILTER (WHERE lower(username) = lower($2)) AS username_count
FROM users
`

type CountUsersByEmailOrUsernameParams struct {
	Lower   string
	Lower_2 string
}

type CountUsersByEmailOrUsernameRow struct {
	EmailCount    int64
	UsernameCount int64
}

// Used to tell a duplicate email from a duplicate username *internally*, without
// the response revealing which one collided.
func (q *Queries) CountUsersByEmailOrUsername(ctx context.Context, arg CountUsersByEmailOrUsernameParams) (CountUsersByEmailOrUsernameRow, error) {
	row := q.db.QueryRow(ctx, countUsersByEmailOrUsername, arg.Lower, arg.Lower_2)
	var i CountUsersByEmailOrUsernameRow
	err := row.Scan(&i.EmailCount, &i.UsernameCount)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, username, password_hash, role, verified, avatar_url, level, star_points, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	Username     string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Verified,
		&i.AvatarUrl,
		&i.Level,
		&i.StarPoints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password_hash, role, verified, avatar_url, level, star_points, created_at, updated_at FROM users WHERE lower(email) = lower($1)
`

// Addresses are compared case-insensitively, matching the unique index.
func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Verified,
		&i.AvatarUrl,
		&i.Level,
		&i.StarPoints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, password_hash, role, verified, avatar_url, level, star_points, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Verified,
		&i.AvatarUrl,
		&i.Level,
		&i.StarPoints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, password_hash, role, verified, avatar_url, level, star_points, created_at, updated_at FROM users WHERE lower(username) = lower($1)
`

func (q *Queries) GetUserByUsername(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Verified,
		&i.AvatarUrl,
		&i.Level,
		&i.StarPoints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markUserVerified = `-- name: MarkUserVerified :one
UPDATE users SET verified = true WHERE id = $1 RETURNING id, email, username, password_hash, role, verified, avatar_url, level, star_points, created_at, updated_at
`

func (q *Queries) MarkUserVerified(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, markUserVerified, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Verified,
		&i.AvatarUrl,
		&i.Level,
		&i.StarPoints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
